# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import control_center_pb2 as control__center__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in control_center_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlServiceStub(object):
    """============================================================================
    Service Definitions
    ============================================================================

    / Control Service - Main API for CLI clients
    /
    / All methods require JWT token authentication via gRPC metadata.
    / Token should be passed as: metadata[('authorization', 'Bearer <token>')]
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAgentInfo = channel.unary_unary(
                '/control_center.ControlService/GetAgentInfo',
                request_serializer=control__center__pb2.AgentInfoRequest.SerializeToString,
                response_deserializer=control__center__pb2.AgentInfo.FromString,
                _registered_method=True)
        self.ExecuteCommand = channel.unary_unary(
                '/control_center.ControlService/ExecuteCommand',
                request_serializer=control__center__pb2.CommandRequest.SerializeToString,
                response_deserializer=control__center__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.ExecuteCommandStream = channel.stream_stream(
                '/control_center.ControlService/ExecuteCommandStream',
                request_serializer=control__center__pb2.CommandRequest.SerializeToString,
                response_deserializer=control__center__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.MonitorConnection = channel.unary_stream(
                '/control_center.ControlService/MonitorConnection',
                request_serializer=control__center__pb2.MonitorRequest.SerializeToString,
                response_deserializer=control__center__pb2.ConnectionStatus.FromString,
                _registered_method=True)


class ControlServiceServicer(object):
    """============================================================================
    Service Definitions
    ============================================================================

    / Control Service - Main API for CLI clients
    /
    / All methods require JWT token authentication via gRPC metadata.
    / Token should be passed as: metadata[('authorization', 'Bearer <token>')]
    """

    def GetAgentInfo(self, request, context):
        """Get information about the connected agent

        Requires: Valid JWT token in metadata
        Returns: OS type, version, and available capabilities
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCommand(self, request, context):
        """Execute a single command on the agent

        Requires: Valid JWT token in metadata
        Rate limited to 100 requests per minute per user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCommandStream(self, request_iterator, context):
        """Execute multiple commands via bidirectional streaming

        Requires: Valid JWT token in metadata
        Responses are returned in the same order as requests
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MonitorConnection(self, request, context):
        """Monitor connection status to the agent

        Requires: Valid JWT token in metadata
        Updates sent every 5 seconds
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAgentInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentInfo,
                    request_deserializer=control__center__pb2.AgentInfoRequest.FromString,
                    response_serializer=control__center__pb2.AgentInfo.SerializeToString,
            ),
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=control__center__pb2.CommandRequest.FromString,
                    response_serializer=control__center__pb2.CommandResponse.SerializeToString,
            ),
            'ExecuteCommandStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ExecuteCommandStream,
                    request_deserializer=control__center__pb2.CommandRequest.FromString,
                    response_serializer=control__center__pb2.CommandResponse.SerializeToString,
            ),
            'MonitorConnection': grpc.unary_stream_rpc_method_handler(
                    servicer.MonitorConnection,
                    request_deserializer=control__center__pb2.MonitorRequest.FromString,
                    response_serializer=control__center__pb2.ConnectionStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'control_center.ControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('control_center.ControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlService(object):
    """============================================================================
    Service Definitions
    ============================================================================

    / Control Service - Main API for CLI clients
    /
    / All methods require JWT token authentication via gRPC metadata.
    / Token should be passed as: metadata[('authorization', 'Bearer <token>')]
    """

    @staticmethod
    def GetAgentInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control_center.ControlService/GetAgentInfo',
            control__center__pb2.AgentInfoRequest.SerializeToString,
            control__center__pb2.AgentInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control_center.ControlService/ExecuteCommand',
            control__center__pb2.CommandRequest.SerializeToString,
            control__center__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCommandStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/control_center.ControlService/ExecuteCommandStream',
            control__center__pb2.CommandRequest.SerializeToString,
            control__center__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MonitorConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/control_center.ControlService/MonitorConnection',
            control__center__pb2.MonitorRequest.SerializeToString,
            control__center__pb2.ConnectionStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AgentServiceStub(object):
    """/ Agent Service - Internal API for server-to-agent communication
    /
    / This service runs on the agent (inside container) and is only
    / accessible from localhost. It trusts the server's validation.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInfo = channel.unary_unary(
                '/control_center.AgentService/GetInfo',
                request_serializer=control__center__pb2.InfoRequest.SerializeToString,
                response_deserializer=control__center__pb2.AgentInfo.FromString,
                _registered_method=True)
        self.Execute = channel.unary_unary(
                '/control_center.AgentService/Execute',
                request_serializer=control__center__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=control__center__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/control_center.AgentService/Ping',
                request_serializer=control__center__pb2.PingRequest.SerializeToString,
                response_deserializer=control__center__pb2.PongResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """/ Agent Service - Internal API for server-to-agent communication
    /
    / This service runs on the agent (inside container) and is only
    / accessible from localhost. It trusts the server's validation.
    """

    def GetInfo(self, request, context):
        """Get agent information (OS, version, capabilities)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Execute a command on the local system

        Commands are executed based on OS type:
        - Windows: Write to C:\mouse_cmd.txt or C:\keyboard_cmd.txt
        - macOS: Execute via cliclick
        - Linux: Execute via xdotool
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Health check ping
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=control__center__pb2.InfoRequest.FromString,
                    response_serializer=control__center__pb2.AgentInfo.SerializeToString,
            ),
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=control__center__pb2.ExecuteRequest.FromString,
                    response_serializer=control__center__pb2.ExecuteResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=control__center__pb2.PingRequest.FromString,
                    response_serializer=control__center__pb2.PongResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'control_center.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('control_center.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """/ Agent Service - Internal API for server-to-agent communication
    /
    / This service runs on the agent (inside container) and is only
    / accessible from localhost. It trusts the server's validation.
    """

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control_center.AgentService/GetInfo',
            control__center__pb2.InfoRequest.SerializeToString,
            control__center__pb2.AgentInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control_center.AgentService/Execute',
            control__center__pb2.ExecuteRequest.SerializeToString,
            control__center__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control_center.AgentService/Ping',
            control__center__pb2.PingRequest.SerializeToString,
            control__center__pb2.PongResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
