# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import control_center_pb2 as control__center__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in control_center_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlServiceStub(object):
    """============================================================================
    SERVICE DEFINITIONS
    ============================================================================

    Main control service (server-side)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterAgent = channel.unary_unary(
                '/control_center.ControlService/RegisterAgent',
                request_serializer=control__center__pb2.RegistrationRequest.SerializeToString,
                response_deserializer=control__center__pb2.RegistrationResponse.FromString,
                _registered_method=True)
        self.AgentStream = channel.stream_stream(
                '/control_center.ControlService/AgentStream',
                request_serializer=control__center__pb2.AgentMessage.SerializeToString,
                response_deserializer=control__center__pb2.ServerMessage.FromString,
                _registered_method=True)
        self.ExecuteCommand = channel.unary_unary(
                '/control_center.ControlService/ExecuteCommand',
                request_serializer=control__center__pb2.CommandRequest.SerializeToString,
                response_deserializer=control__center__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.MonitorConnection = channel.unary_stream(
                '/control_center.ControlService/MonitorConnection',
                request_serializer=control__center__pb2.MonitorRequest.SerializeToString,
                response_deserializer=control__center__pb2.ConnectionStatus.FromString,
                _registered_method=True)
        self.QueryConnections = channel.unary_unary(
                '/control_center.ControlService/QueryConnections',
                request_serializer=control__center__pb2.ConnectionQuery.SerializeToString,
                response_deserializer=control__center__pb2.ConnectionStatusResponse.FromString,
                _registered_method=True)
        self.QueryServers = channel.unary_unary(
                '/control_center.ControlService/QueryServers',
                request_serializer=control__center__pb2.ServerStatusQuery.SerializeToString,
                response_deserializer=control__center__pb2.ServerStatusResponse.FromString,
                _registered_method=True)
        self.GetServerIdentity = channel.unary_unary(
                '/control_center.ControlService/GetServerIdentity',
                request_serializer=control__center__pb2.InfoRequest.SerializeToString,
                response_deserializer=control__center__pb2.ServerIdentity.FromString,
                _registered_method=True)
        self.GetAgentInfo = channel.unary_unary(
                '/control_center.ControlService/GetAgentInfo',
                request_serializer=control__center__pb2.AgentInfoRequest.SerializeToString,
                response_deserializer=control__center__pb2.AgentInfo.FromString,
                _registered_method=True)
        self.Execute = channel.unary_unary(
                '/control_center.ControlService/Execute',
                request_serializer=control__center__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=control__center__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/control_center.ControlService/Ping',
                request_serializer=control__center__pb2.PingRequest.SerializeToString,
                response_deserializer=control__center__pb2.PongResponse.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/control_center.ControlService/GetMetrics',
                request_serializer=control__center__pb2.MetricsRequest.SerializeToString,
                response_deserializer=control__center__pb2.MetricsResponse.FromString,
                _registered_method=True)


class ControlServiceServicer(object):
    """============================================================================
    SERVICE DEFINITIONS
    ============================================================================

    Main control service (server-side)
    """

    def RegisterAgent(self, request, context):
        """Agent registration (agent calls this when connecting)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AgentStream(self, request_iterator, context):
        """Bidirectional stream between agent and server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCommand(self, request, context):
        """Execute command (CLI to server)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MonitorConnection(self, request, context):
        """Monitor connection (CLI to server)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryConnections(self, request, context):
        """Query connection status (for monitoring)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryServers(self, request, context):
        """Query server status (for monitoring)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerIdentity(self, request, context):
        """Get server identity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentInfo(self, request, context):
        """Legacy compatibility
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Get server metrics (Prometheus format)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=control__center__pb2.RegistrationRequest.FromString,
                    response_serializer=control__center__pb2.RegistrationResponse.SerializeToString,
            ),
            'AgentStream': grpc.stream_stream_rpc_method_handler(
                    servicer.AgentStream,
                    request_deserializer=control__center__pb2.AgentMessage.FromString,
                    response_serializer=control__center__pb2.ServerMessage.SerializeToString,
            ),
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=control__center__pb2.CommandRequest.FromString,
                    response_serializer=control__center__pb2.CommandResponse.SerializeToString,
            ),
            'MonitorConnection': grpc.unary_stream_rpc_method_handler(
                    servicer.MonitorConnection,
                    request_deserializer=control__center__pb2.MonitorRequest.FromString,
                    response_serializer=control__center__pb2.ConnectionStatus.SerializeToString,
            ),
            'QueryConnections': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryConnections,
                    request_deserializer=control__center__pb2.ConnectionQuery.FromString,
                    response_serializer=control__center__pb2.ConnectionStatusResponse.SerializeToString,
            ),
            'QueryServers': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryServers,
                    request_deserializer=control__center__pb2.ServerStatusQuery.FromString,
                    response_serializer=control__center__pb2.ServerStatusResponse.SerializeToString,
            ),
            'GetServerIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerIdentity,
                    request_deserializer=control__center__pb2.InfoRequest.FromString,
                    response_serializer=control__center__pb2.ServerIdentity.SerializeToString,
            ),
            'GetAgentInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentInfo,
                    request_deserializer=control__center__pb2.AgentInfoRequest.FromString,
                    response_serializer=control__center__pb2.AgentInfo.SerializeToString,
            ),
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=control__center__pb2.ExecuteRequest.FromString,
                    response_serializer=control__center__pb2.ExecuteResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=control__center__pb2.PingRequest.FromString,
                    response_serializer=control__center__pb2.PongResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=control__center__pb2.MetricsRequest.FromString,
                    response_serializer=control__center__pb2.MetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'control_center.ControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('control_center.ControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlService(object):
    """============================================================================
    SERVICE DEFINITIONS
    ============================================================================

    Main control service (server-side)
    """

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control_center.ControlService/RegisterAgent',
            control__center__pb2.RegistrationRequest.SerializeToString,
            control__center__pb2.RegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AgentStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/control_center.ControlService/AgentStream',
            control__center__pb2.AgentMessage.SerializeToString,
            control__center__pb2.ServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control_center.ControlService/ExecuteCommand',
            control__center__pb2.CommandRequest.SerializeToString,
            control__center__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MonitorConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/control_center.ControlService/MonitorConnection',
            control__center__pb2.MonitorRequest.SerializeToString,
            control__center__pb2.ConnectionStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryConnections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control_center.ControlService/QueryConnections',
            control__center__pb2.ConnectionQuery.SerializeToString,
            control__center__pb2.ConnectionStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryServers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control_center.ControlService/QueryServers',
            control__center__pb2.ServerStatusQuery.SerializeToString,
            control__center__pb2.ServerStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServerIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control_center.ControlService/GetServerIdentity',
            control__center__pb2.InfoRequest.SerializeToString,
            control__center__pb2.ServerIdentity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgentInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control_center.ControlService/GetAgentInfo',
            control__center__pb2.AgentInfoRequest.SerializeToString,
            control__center__pb2.AgentInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control_center.ControlService/Execute',
            control__center__pb2.ExecuteRequest.SerializeToString,
            control__center__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control_center.ControlService/Ping',
            control__center__pb2.PingRequest.SerializeToString,
            control__center__pb2.PongResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control_center.ControlService/GetMetrics',
            control__center__pb2.MetricsRequest.SerializeToString,
            control__center__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AgentServiceStub(object):
    """Agent service (agent-side) - kept for backwards compatibility if needed
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInfo = channel.unary_unary(
                '/control_center.AgentService/GetInfo',
                request_serializer=control__center__pb2.InfoRequest.SerializeToString,
                response_deserializer=control__center__pb2.AgentInfo.FromString,
                _registered_method=True)
        self.Execute = channel.unary_unary(
                '/control_center.AgentService/Execute',
                request_serializer=control__center__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=control__center__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/control_center.AgentService/Ping',
                request_serializer=control__center__pb2.PingRequest.SerializeToString,
                response_deserializer=control__center__pb2.PongResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """Agent service (agent-side) - kept for backwards compatibility if needed
    """

    def GetInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=control__center__pb2.InfoRequest.FromString,
                    response_serializer=control__center__pb2.AgentInfo.SerializeToString,
            ),
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=control__center__pb2.ExecuteRequest.FromString,
                    response_serializer=control__center__pb2.ExecuteResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=control__center__pb2.PingRequest.FromString,
                    response_serializer=control__center__pb2.PongResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'control_center.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('control_center.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """Agent service (agent-side) - kept for backwards compatibility if needed
    """

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control_center.AgentService/GetInfo',
            control__center__pb2.InfoRequest.SerializeToString,
            control__center__pb2.AgentInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control_center.AgentService/Execute',
            control__center__pb2.ExecuteRequest.SerializeToString,
            control__center__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control_center.AgentService/Ping',
            control__center__pb2.PingRequest.SerializeToString,
            control__center__pb2.PongResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
