// crates/agent/src/main.rs

use tonic::{Request, Response, Status};
use tracing::{info, warn, error, debug};
use std::process::Command as ProcessCommand;
use std::time::Instant;
#[cfg(any(target_os = "linux", target_os = "windows"))]
use regex::Regex;

// Protobuf definitions generated by tonic
mod proto {
    tonic::include_proto!("control_center");
}

mod identity;
mod connection;

// Re-exporting for easier access
use proto::{
    agent_service_server::AgentService,
};

// For cross-platform OS detection
use proto::{
    AgentInfo,
    ExecuteRequest, 
    ExecuteResponse,
    InfoRequest,
    PingRequest, 
    PongResponse,
    OsType,
};

// Mouse position data structure
#[derive(Debug, Clone)]
struct MousePosition {
    x: i32,
    y: i32,
    captured: bool,
}

// Detailed action information
#[derive(Debug, Clone)]
struct ActionDetails {
    action_type: String,  // "left", "right", "double", "drag", etc.
    is_mouse: bool,
    is_here_command: bool,
}

/// Agent implementation
pub struct AgentServiceImpl {
    os_type: OsType,
    os_version: String,
    capabilities: Vec<String>,
    #[cfg(target_os = "macos")]
    cliclick_path: Option<String>,
}

/// Core implementation of the AgentService
impl AgentServiceImpl {
    pub fn new() -> Self {
        let (os_type, os_version) = Self::detect_os_version();
        let capabilities = Self::detect_capabilities(&os_type);
        
        info!("Agent initialized with position tracking");
        info!("  OS: {:?}", os_type);
        info!("  Version: {}", os_version);
        info!("  Capabilities: {:?}", capabilities);
        
        Self {
            os_type,
            os_version,
            capabilities,
            #[cfg(target_os = "macos")]
            cliclick_path: Self::resolve_cliclick_path(),
        }
    }

    #[cfg(target_os = "macos")]
    fn resolve_cliclick_path() -> Option<String> {
        let paths = [
            "/usr/local/bin/cliclick",
            "/opt/homebrew/bin/cliclick",
            "cliclick",
        ];
        for p in &paths {
            if ProcessCommand::new(p).arg("--version").output().is_ok() {
                return Some(p.to_string());
            }
        }
        None
    }
    
    /// Real OS detection with version information
    fn detect_os_version() -> (OsType, String) {
        #[cfg(target_os = "windows")]
        {
            Self::detect_windows_version()
        }
        
        #[cfg(target_os = "macos")]
        {
            Self::detect_macos_version()
        }
        
        #[cfg(target_os = "linux")]
        {
            Self::detect_linux_version()
        }
    }
    
    /// Windows version detection using registry
    #[cfg(target_os = "windows")]
    fn detect_windows_version() -> (OsType, String) {
        use winreg::enums::*;
        use winreg::RegKey;
        
        let hklm = RegKey::predef(HKEY_LOCAL_MACHINE);
        
        if let Ok(current_version) = hklm.open_subkey("SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion") {
            let product_name: String = current_version.get_value("ProductName").unwrap_or_else(|_| "Windows".to_string());
            let display_version: String = current_version.get_value("DisplayVersion").unwrap_or_else(|_| String::new());
            let current_build: String = current_version.get_value("CurrentBuild").unwrap_or_else(|_| String::new());
            
            let version = if !display_version.is_empty() && !current_build.is_empty() {
                format!("{} {} (Build {})", product_name, display_version, current_build)
            } else if !current_build.is_empty() {
                format!("{} (Build {})", product_name, current_build)
            } else {
                product_name
            };
            
            return (OsType::Windows, version);
        }
        
        (OsType::Windows, "Windows (Unknown Version)".to_string())
    }
    
    /// Linux version detection using /etc/os-release and fallback methods
    #[cfg(target_os = "linux")]
    fn detect_linux_version() -> (OsType, String) {
        use std::fs;
        // Try /etc/os-release first (systemd standard)
        if let Ok(content) = fs::read_to_string("/etc/os-release") {
            let mut pretty_name = None;
            
            for line in content.lines() {
                if line.starts_with("PRETTY_NAME=") {
                    pretty_name = Some(
                        line.split('=')
                            .nth(1)
                            .unwrap_or("")
                            .trim_matches('"')
                            .to_string()
                    );
                    break;
                }
            }
            
            if let Some(name) = pretty_name {
                return (OsType::Linux, name);
            }
        }
        
        // Fallback: try lsb_release command
        if let Ok(output) = ProcessCommand::new("lsb_release").arg("-d").output() {
            if let Ok(description) = String::from_utf8(output.stdout) {
                if let Some(version) = description.split(':').nth(1) {
                    return (OsType::Linux, version.trim().to_string());
                }
            }
        }
        
        // Last resort: try uname
        if let Ok(output) = ProcessCommand::new("uname").arg("-sr").output() {
            if let Ok(version) = String::from_utf8(output.stdout) {
                return (OsType::Linux, version.trim().to_string());
            }
        }
        
        (OsType::Linux, "Linux (Unknown Distribution)".to_string())
    }
    
    /// macOS version detection using sw_vers
    #[cfg(target_os = "macos")]
    fn detect_macos_version() -> (OsType, String) {
        // Get macOS version using sw_vers
        if let Ok(output) = ProcessCommand::new("sw_vers").arg("-productVersion").output() {
            if let Ok(version) = String::from_utf8(output.stdout) {
                let version = version.trim();
                
                // Get build number
                if let Ok(build_output) = ProcessCommand::new("sw_vers").arg("-buildVersion").output() {
                    if let Ok(build) = String::from_utf8(build_output.stdout) {
                        return (
                            OsType::Macos,
                            format!("macOS {} (Build {})", version, build.trim())
                        );
                    }
                }
                
                return (OsType::Macos, format!("macOS {}", version));
            }
        }
        
        (OsType::Macos, "macOS (Unknown Version)".to_string())
    }
    
    /// Detect available capabilities
    fn detect_capabilities(os_type: &OsType) -> Vec<String> {
        let mut capabilities = vec!["mouse".to_string(), "keyboard".to_string(), "position_tracking".to_string()];
        
        match os_type {
            OsType::Windows => {
                capabilities.push("file_based_control".to_string());
            }
            OsType::Macos => {
                // Check if cliclick is available
                if ProcessCommand::new("which").arg("cliclick").output().is_ok() {
                    capabilities.push("cliclick".to_string());
                } else {
                    warn!("cliclick not found - install with: brew install cliclick");
                }
            }
            OsType::Linux => {
                // Check if xdotool is available
                if ProcessCommand::new("which").arg("xdotool").output().is_ok() {
                    capabilities.push("xdotool".to_string());
                } else {
                    warn!("xdotool not found - install with: sudo apt-get install xdotool");
                }
            }
        }
        
        capabilities
    }
    
    /// Validate command before execution
    fn validate_command(&self, command: &str) -> Result<(), String> {
        if command.is_empty() {
            return Err("Command cannot be empty".to_string());
        }
        
        if command.len() > 10000 {
            return Err("Command exceeds maximum length (10000 characters)".to_string());
        }
        
        // Check for dangerous patterns (basic protection)
        let dangerous_patterns = [
            "rm -rf /",
            "format c:",
            "dd if=/dev/zero",
            ":(){ :|:& };:",  // Fork bomb
            "mkfs",
            "shutdown",
            "reboot",
        ];
        
        for pattern in &dangerous_patterns {
            if command.to_lowercase().contains(&pattern.to_lowercase()) {
                warn!("Blocked potentially dangerous command: {}", command);
                return Err(format!("Command contains blocked pattern: {}", pattern));
            }
        }
        
        Ok(())
    }
    
    // BUG-008 FIX ─────────────────────────────────────────────────────────────
    // The Python actuation layer translates human commands ("960 540 left") into
    // OS-level shell commands before sending them to the agent.  parse_action_details()
    // was receiving those raw OS strings, so build_detailed_message() logged entries
    // like {"action": "Typed: cmd /c echo 960 540 left > C:\mouse_cmd.txt"}.
    //
    // extract_human_command() reverses the platform translation so that
    // parse_action_details() and build_detailed_message() always work with the
    // original semantic command string.
    // ─────────────────────────────────────────────────────────────────────────

    /// Extract a human-readable command from the raw OS command sent by the
    /// Python actuation layer.
    fn extract_human_command(&self, command: &str) -> String {
        // ── Windows ──────────────────────────────────────────────────────────
        // Pattern: "cmd /c echo <human_cmd> > C:\mouse_cmd.txt"
        //      or: "cmd /c echo <human_cmd> > C:\keyboard_cmd.txt"
        // Extract the text between "echo " and " > C:\".
        if command.starts_with("cmd /c echo ") {
            let after_echo = &command["cmd /c echo ".len()..];
            if let Some(pos) = after_echo.find(" > C:\\") {
                return after_echo[..pos].trim().to_string();
            }
        }

        // ── Linux xdotool ────────────────────────────────────────────────────
        // Pattern: "DISPLAY=:0 xdotool <sub-command> …"
        // Reconstruct a human command from the xdotool syntax.
        if command.contains("xdotool") {
            return self.extract_xdotool_human_command(command);
        }

        // ── macOS osascript (pure keyboard commands: type / key code) ─────────
        if command.starts_with("osascript") {
            return self.extract_osascript_human_command(command);
        }

        // ── macOS cliclick ───────────────────────────────────────────────────
        if command.contains("cliclick") {
            return self.extract_cliclick_human_command(command);
        }

        // Fallback – return unchanged.
        command.to_string()
    }

    /// Parse a cliclick command string and return a human-readable equivalent.
    fn extract_cliclick_human_command(&self, command: &str) -> String {
        // Strip leading "cliclick" or full path e.g. "/usr/local/bin/cliclick"
        let after = command
            .split_whitespace()
            .skip_while(|s| s.ends_with("cliclick"))
            .collect::<Vec<&str>>()
            .join(" ");

        let tokens: Vec<&str> = after.split_whitespace().collect();
        if tokens.is_empty() {
            return command.to_string();
        }

        // Each token is an action shortcut e.g. "c:.", "rc:960,540", "t:hello"
        // We only need the first action token to determine the human command type.
        let action_token = tokens[0];

        // Keyboard: "t:text" → "type text", "kp:return" → "press {Enter}"
        if let Some(text) = action_token.strip_prefix("t:") {
            return format!("type {}", text.trim_matches('"'));
        }
        if let Some(key) = action_token.strip_prefix("kp:") {
            return format!("press {{{}}}", key);
        }
        if action_token.starts_with("kd:") {
            return self.parse_cliclick_key_sequence(&tokens);
        }
        if action_token.starts_with("ku:") {
            return format!("press {}", tokens.join(" "));
        }

        // Mouse: parse shortcut prefix and coordinates
        // Shortcuts: c=left, rc=right, dc=double, tc=triple, mc=middle,
        //            dd=hold, du=release, m=move, p=position
        let (shortcut, coords) = if let Some(pos) = action_token.find(':') {
            (&action_token[..pos], &action_token[pos+1..])
        } else {
            return command.to_string();
        };

        let is_here = coords == ".";
        let coord_str = if is_here {
            String::new()
        } else {
            // "960,540" → "960 540"
            coords.replace(',', " ")
        };

        let action = match shortcut {
            "c"  => "left",
            "rc" => "right",
            "dc" => "double",
            "tc" => "triple",
            "mc" => "middle",
            "dd" => "hold",
            "du" => "release",
            "m"  => "move",
            "p"  => return "position".to_string(),
            _    => "left",
        };

        if is_here {
            format!("here {}", action)
        } else {
            format!("{} {}", coord_str, action)
        }
    }

    fn extract_osascript_human_command(&self, command: &str) -> String {
        // keystroke "text"  →  "type text"
        if command.contains("keystroke") {
            if let Some(start) = command.find("keystroke \"") {
                let after = &command[start + "keystroke \"".len()..];
                if let Some(end) = after.find('"') {
                    return format!("type {}", &after[..end]);
                }
            }
            return "type".to_string();
        }

        // key code N [using {mods}]  →  "press [mods]{KeyName}"
        if command.contains("key code") {
            let key_name: &str = if let Some(code_pos) = command.find("key code ") {
                let after = &command[code_pos + "key code ".len()..];
                let code_str: String = after.chars().take_while(|c| c.is_ascii_digit()).collect();
                match code_str.parse::<u32>() {
                    Ok(36)  => "{Enter}",
                    Ok(48)  => "{Tab}",
                    Ok(51)  => "{Backspace}",
                    Ok(53)  => "{Esc}",
                    Ok(117) => "{Delete}",
                    Ok(116) => "{PgUp}",
                    Ok(121) => "{PgDn}",
                    Ok(115) => "{Home}",
                    Ok(119) => "{End}",
                    Ok(123) => "{Left}",
                    Ok(124) => "{Right}",
                    Ok(125) => "{Down}",
                    Ok(126) => "{Up}",
                    _       => "",
                }
            } else {
                ""
            };

            let mut mods = String::new();
            if command.contains("command down") { mods.push('#'); }
            if command.contains("option down")  { mods.push('!'); }
            if command.contains("control down") { mods.push('^'); }
            if command.contains("shift down")   { mods.push('+'); }

            if !key_name.is_empty() || !mods.is_empty() {
                return format!("press {}{}", mods, key_name);
            }
        }

        command.to_string()
    }

    fn parse_cliclick_key_sequence(&self, tokens: &[&str]) -> String {
        let mut modifiers = String::new();
        let mut key       = String::new();

        for token in tokens {
            if let Some(mods_str) = token.strip_prefix("kd:") {
                for m in mods_str.split(',') {
                    let sym = match m.trim() {
                        "cmd"   => "#",
                        "alt"   => "!",
                        "ctrl"  => "^",
                        "shift" => "+",
                        _       => "",
                    };
                    modifiers.push_str(sym);
                }
            } else if let Some(text) = token.strip_prefix("t:") {
                key = text.trim_matches('"').to_string();
            } else if let Some(key_name) = token.strip_prefix("kp:") {
                key = match key_name {
                    "return"      => "{Enter}",
                    "tab"         => "{Tab}",
                    "delete"      => "{Backspace}",
                    "fwd-delete"  => "{Delete}",
                    "arrow-up"    => "{Up}",
                    "arrow-down"  => "{Down}",
                    "arrow-left"  => "{Left}",
                    "arrow-right" => "{Right}",
                    "page-up"     => "{PgUp}",
                    "page-down"   => "{PgDn}",
                    "home"        => "{Home}",
                    "end"         => "{End}",
                    "esc"         => "{Esc}",
                    "space"       => "{Space}",
                    "f1"  => "{F1}",  "f2"  => "{F2}",  "f3"  => "{F3}",  "f4"  => "{F4}",
                    "f5"  => "{F5}",  "f6"  => "{F6}",  "f7"  => "{F7}",  "f8"  => "{F8}",
                    "f9"  => "{F9}",  "f10" => "{F10}", "f11" => "{F11}", "f12" => "{F12}",
                    other => other,
                }.to_string();
            }
            // ku: tokens are key-up cleanup — skip them
        }

        if !modifiers.is_empty() || !key.is_empty() {
            format!("press {}{}", modifiers, key)
        } else {
            format!("press {}", tokens.join(" "))
        }
    }

    // Convert a key string with modifiers into a human-readable format
    fn format_keys_for_display(&self, keys: &str) -> String {
        let mod_names: &[(&str, &str)] = match self.os_type {
            OsType::Macos   => &[("#", "Cmd"),   ("!", "Option"), ("^", "Ctrl"), ("+", "Shift")],
            OsType::Windows => &[("#", "Win"),   ("!", "Alt"),    ("^", "Ctrl"), ("+", "Shift")],
            OsType::Linux   => &[("#", "Super"), ("!", "Alt"),    ("^", "Ctrl"), ("+", "Shift")],
        };

        let special_name = |k: &str| -> Option<&'static str> {
            match k {
                "{Enter}" | "{Return}" => Some("Return"),
                "{Tab}"                => Some("Tab"),
                "{Esc}" | "{Escape}"   => Some("Esc"),
                "{Backspace}" | "{BS}" => Some("Delete"),
                "{Delete}" | "{Del}"   => Some("Fwd Delete"),
                "{Space}"              => Some("Space"),
                "{Up}"                 => Some("Up"),
                "{Down}"               => Some("Down"),
                "{Left}"               => Some("Left"),
                "{Right}"              => Some("Right"),
                "{Home}"               => Some("Home"),
                "{End}"                => Some("End"),
                "{PgUp}"               => Some("Page Up"),
                "{PgDn}"               => Some("Page Down"),
                "{F1}"  => Some("F1"),  "{F2}"  => Some("F2"),
                "{F3}"  => Some("F3"),  "{F4}"  => Some("F4"),
                "{F5}"  => Some("F5"),  "{F6}"  => Some("F6"),
                "{F7}"  => Some("F7"),  "{F8}"  => Some("F8"),
                "{F9}"  => Some("F9"),  "{F10}" => Some("F10"),
                "{F11}" => Some("F11"), "{F12}" => Some("F12"),
                _       => None,
            }
        };

        // Fast path: whole string is a bare special key
        if let Some(name) = special_name(keys) {
            return name.to_string();
        }

        let modifier_syms: &[char] = &['#', '!', '^', '+'];
        let mut parts: Vec<String> = Vec::new();
        let mut byte_pos = 0usize;

        for ch in keys.chars() {
            if !modifier_syms.contains(&ch) { break; }
            let sym = &keys[byte_pos..byte_pos + ch.len_utf8()];
            if let Some((_, name)) = mod_names.iter().find(|(s, _)| *s == sym) {
                parts.push(name.to_string());
            }
            byte_pos += ch.len_utf8();
        }

        let key_part = &keys[byte_pos..];
        if !key_part.is_empty() {
            if let Some(name) = special_name(key_part) {
                parts.push(name.to_string());
            } else if key_part.starts_with('{') && key_part.ends_with('}') {
                parts.push(key_part[1..key_part.len() - 1].to_string());
            } else if key_part.chars().count() == 1 {
                parts.push(key_part.to_uppercase());
            } else {
                parts.push(key_part.to_string());
            }
        }

        if parts.is_empty() { keys.to_string() } else { parts.join("+") }
    }

    /// Parse an xdotool command string and return a human-readable equivalent.
    fn extract_xdotool_human_command(&self, command: &str) -> String {
        let tokens: Vec<&str> = command.split_whitespace().collect();

        // Locate "xdotool" and take everything after it as the sub-command.
        let xdotool_idx = match tokens.iter().position(|&t| t == "xdotool") {
            Some(i) => i,
            None => return command.to_string(),
        };
        let sub = &tokens[xdotool_idx + 1..];

        if sub.is_empty() {
            return command.to_string();
        }

        match sub[0] {
            // "DISPLAY=:0 xdotool getmouselocation --shell" → "position"
            "getmouselocation" => "position".to_string(),

            // "DISPLAY=:0 xdotool type \"Hello World\"" → "type Hello World"
            "type" => {
                let text = sub[1..].join(" ").trim_matches('"').to_string();
                format!("type {}", text)
            }

            // "DISPLAY=:0 xdotool key ctrl+c" → "press ctrl+c"
            "key" => {
                let keys = sub[1..].join(" ");
                format!("press {}", keys)
            }

            // "DISPLAY=:0 xdotool mousemove X Y [...]"
            "mousemove" => {
                if sub.len() < 3 {
                    return command.to_string();
                }
                let x = sub[1];
                let y = sub[2];

                if sub.len() == 3 {
                    // Pure move: "X Y move"
                    return format!("{} {} move", x, y);
                }

                match sub[3] {
                    "click" => {
                        // "xdotool mousemove X Y click [--repeat N] [--clearmodifiers] BTN"
                        self.parse_xdotool_click_tokens(&sub[3..], Some((x, y)))
                    }
                    "mousedown" => {
                        // Drag: "xdotool mousemove X Y mousedown 1 mousemove X2 Y2 mouseup 1"
                        // Find the second "mousemove" to get the destination.
                        let dest = sub[4..].windows(3).find(|w| w[0] == "mousemove");
                        if let Some(m) = dest {
                            if m.len() >= 3 {
                                return format!("{} {} drag {} {}", x, y, m[1], m[2]);
                            }
                        }
                        format!("{} {} drag", x, y)
                    }
                    _ => format!("{} {} move", x, y),
                }
            }

            // "DISPLAY=:0 xdotool click [--repeat N] BTN" → "here <action>"
            "click" => self.parse_xdotool_click_tokens(sub, None),

            _ => command.to_string(),
        }
    }

    /// Convert an xdotool `click` token slice into a human action string.
    ///
    /// `tokens[0]` must be `"click"`.
    /// `coords` is `Some((x, y))` for coordinate-based commands, `None` for "here".
    fn parse_xdotool_click_tokens(&self, tokens: &[&str], coords: Option<(&str, &str)>) -> String {
        let prefix = match coords {
            Some((x, y)) => format!("{} {} ", x, y),
            None => "here ".to_string(),
        };

        let mut i = 1usize; // skip "click"
        let mut repeat: Option<&str> = None;

        if tokens.get(i) == Some(&"--repeat") {
            repeat = tokens.get(i + 1).copied();
            i += 2;
        }
        if tokens.get(i) == Some(&"--clearmodifiers") {
            i += 1;
        }

        let button = tokens.get(i).copied().unwrap_or("1");

        match button {
            "1" => match repeat {
                Some("2") => format!("{}double", prefix),
                Some(_)   => format!("{}double", prefix), // --repeat N means double/multi
                None      => format!("{}left", prefix),
            },
            "2" => format!("{}middle", prefix),
            "3" => format!("{}right", prefix),
            "4" => match repeat {
                Some(n) => format!("{}scroll_up {}", prefix, n),
                None    => format!("{}scroll_up", prefix),
            },
            "5" => match repeat {
                Some(n) => format!("{}scroll_down {}", prefix, n),
                None    => format!("{}scroll_down", prefix),
            },
            _ => format!("{}left", prefix),
        }
    }

    // ── end BUG-008 helpers ───────────────────────────────────────────────────
    fn parse_action_details(&self, command: &str) -> ActionDetails {
        let tokens: Vec<&str> = command.split_whitespace().collect();

        let is_here = tokens.get(0) == Some(&"here");

        let action_type = if tokens.len() >= 3 && tokens[0].parse::<i32>().is_ok() {
            // Coordinate-based: "960 540 left"
            tokens.get(2).unwrap_or(&"move").to_string()
        } else if is_here && tokens.len() >= 2 {
            // Here command: "here left", "here hold", "here release"
            tokens[1].to_string()
        } else if tokens.get(0) == Some(&"position") {
            "position".to_string()
        } else if tokens.get(0) == Some(&"press") {
            // "press {Enter}", "press ^c" — keyboard, not mouse
            "press".to_string()
        } else if command.contains("click") {
            "click".to_string()
        } else if command.contains("drag") {
            "drag".to_string()
        } else if command.contains("type") || command.contains("key") {
            "keyboard".to_string()
        } else {
            "unknown".to_string()
        };

        let is_mouse = matches!(
            action_type.as_str(),
            "left" | "right" | "middle" | "double" | "triple"
            | "click" | "drag" | "move"
            | "scroll_up" | "scroll_down"
            | "hold" | "release"     // mouse button hold/release
            | "position"             // position query
        );

        ActionDetails {
            action_type,
            is_mouse,
            is_here_command: is_here,
        }
    }
    
    // Capture mouse position after execution
    async fn capture_mouse_position(&self) -> MousePosition {
        match self.os_type {
            OsType::Linux => self.capture_position_linux().await,
            OsType::Windows => self.capture_position_windows().await,
            OsType::Macos => self.capture_position_macos().await,
        }
    }
    
    #[cfg(target_os = "linux")]
    async fn capture_position_linux(&self) -> MousePosition {
        match ProcessCommand::new("sh")
            .arg("-c")
            .arg("DISPLAY=${DISPLAY:-:0} xdotool getmouselocation --shell")
            .output()
        {
            Ok(output) if output.status.success() => {
                let stdout = String::from_utf8_lossy(&output.stdout);
                let x_regex = Regex::new(r"X=(\d+)").unwrap();
                let y_regex = Regex::new(r"Y=(\d+)").unwrap();
                
                if let (Some(x_cap), Some(y_cap)) = (x_regex.captures(&stdout), y_regex.captures(&stdout)) {
                    if let (Ok(x), Ok(y)) = (x_cap[1].parse::<i32>(), y_cap[1].parse::<i32>()) {
                        debug!("Position captured: ({}, {})", x, y);
                        return MousePosition { x, y, captured: true };
                    }
                }
            }
            _ => {}
        }
        MousePosition { x: 0, y: 0, captured: false }
    }
    
    #[cfg(target_os = "windows")]
    async fn capture_position_windows(&self) -> MousePosition {
        use winreg::enums::{HKEY_CURRENT_USER, KEY_READ};
        use winreg::RegKey;

        let hkcu = RegKey::predef(HKEY_CURRENT_USER);
        if let Ok(key) = hkcu.open_subkey_with_flags("Software\\MouseTracker", KEY_READ) {
            if let (Ok(x_str), Ok(y_str)) = (
                key.get_value::<String, _>("MouseX"),
                key.get_value::<String, _>("MouseY"),
            ) {
                if let (Ok(x), Ok(y)) = (x_str.parse::<i32>(), y_str.parse::<i32>()) {
                    debug!("Position captured from registry: ({}, {})", x, y);
                    return MousePosition { x, y, captured: true };
                }
            }
        }

        MousePosition { x: 0, y: 0, captured: false }
    }
    
    #[cfg(target_os = "macos")]
    async fn capture_position_macos(&self) -> MousePosition {
        let cliclick_paths = ["/usr/local/bin/cliclick", "/opt/homebrew/bin/cliclick", "cliclick"];
        
        for cliclick_path in &cliclick_paths {
            if let Ok(output) = ProcessCommand::new(cliclick_path).arg("p:.").output() {
                if output.status.success() {
                    let stdout = String::from_utf8_lossy(&output.stdout).trim().to_string();
                    let parts: Vec<&str> = stdout.split(',').collect();
                    
                    if parts.len() == 2 {
                        if let (Ok(x), Ok(y)) = (parts[0].parse::<i32>(), parts[1].parse::<i32>()) {
                            debug!("Position captured: ({}, {})", x, y);
                            return MousePosition { x, y, captured: true };
                        }
                    }
                }
            }
        }
        MousePosition { x: 0, y: 0, captured: false }
    }
    
    // Cross-compilation stubs
    #[cfg(not(target_os = "linux"))]
    async fn capture_position_linux(&self) -> MousePosition {
        MousePosition { x: 0, y: 0, captured: false }
    }
    
    #[cfg(not(target_os = "windows"))]
    async fn capture_position_windows(&self) -> MousePosition {
        MousePosition { x: 0, y: 0, captured: false }
    }
    
    #[cfg(not(target_os = "macos"))]
    async fn capture_position_macos(&self) -> MousePosition {
        MousePosition { x: 0, y: 0, captured: false }
    }
    
    // Build detailed message with action and position
    fn build_detailed_message(
        &self,
        action: &ActionDetails,
        position: &MousePosition,
        command: &str,
    ) -> String {
        // ── Keyboard actions ─────────────────────────────────────────────────────
        if action.action_type == "press" {
            let keys = command.trim_start_matches("press").trim();
            return format!("Pressed: {}", self.format_keys_for_display(keys));
        }
        if action.action_type == "keyboard" {
            // "type x.ai/careers" → "Typed: x.ai/careers"
            let content = command.trim_start_matches("type").trim();
            return format!("Typed: {}", content);
        }
        if !action.is_mouse {
            return format!("Typed: {}", command);
        }

        // ── Position query ───────────────────────────────────────────────────────
        if action.action_type == "position" {
            return if position.captured {
                format!("Position: X={}, Y={}", position.x, position.y)
            } else {
                "Position: (?, ?)".to_string()
            };
        }

        // ── Mouse actions that don't need position ───────────────────────────────
        if !position.captured {
            return format!("Executed: {}", command);
        }

        // ── Mouse actions with position ──────────────────────────────────────────
        let action_name = match action.action_type.as_str() {
            "left"         => "Left-clicked",
            "right"        => "Right-clicked",
            "middle"       => "Middle-clicked",
            "double"       => "Double-clicked",
            "triple"       => "Triple-clicked",
            "drag"         => "Dragged",
            "move"         => "Moved cursor to",
            "scroll_up"    => "Scrolled up at",
            "scroll_down"  => "Scrolled down at",
            "hold"         => "Held button at",
            "release"      => "Released button at",
            _              => "Performed action at",
        };

        if action.is_here_command {
            format!("{} at X={}, Y={}", action_name, position.x, position.y)
        } else if action.action_type == "drag" {
            let tokens: Vec<&str> = command.split_whitespace().collect();
            if tokens.len() >= 5 {
                if let (Ok(x1), Ok(y1), Ok(x2), Ok(y2)) = (
                    tokens[0].parse::<i32>(),
                    tokens[1].parse::<i32>(),
                    tokens[3].parse::<i32>(),
                    tokens[4].parse::<i32>(),
                ) {
                    return format!("Dragged from X={}, Y={} to X={}, Y={}", x1, y1, x2, y2);
                }
            }
            format!("Dragged to X={}, Y={}", position.x, position.y)
        } else {
            format!("{} at X={}, Y={}", action_name, position.x, position.y)
        }
    }
    
    // Execute command with position tracking
    async fn execute_command(&self, command: &str) -> (Result<String, String>, MousePosition, ActionDetails) {
        // Validate first
        if let Err(e) = self.validate_command(command) {
            let empty_action = ActionDetails {
                action_type: "none".to_string(),
                is_mouse: false,
                is_here_command: false,
            };
            return (Err(e), MousePosition { x: 0, y: 0, captured: false }, empty_action);
        }

        // Derive the human command first so parse_action_details works on
        // "here left" not "cmd /c echo here left > C:\mouse_cmd.txt".
        // Without this, is_mouse is always false and position is never captured.
        let human_cmd = self.extract_human_command(command);
        let action = self.parse_action_details(&human_cmd);

        // Execute the command
        let result = match self.os_type {
            OsType::Windows => self.execute_windows(command).await,
            OsType::Macos => self.execute_macos(command).await,
            OsType::Linux => self.execute_linux(command).await,
        };

        // Capture position if it's a mouse action
        let position = if action.is_mouse && result.is_ok() {
            #[cfg(target_os = "windows")]
            {
                let wait_ms = if action.is_here_command { 10 } else { 20 };
                tokio::time::sleep(tokio::time::Duration::from_millis(wait_ms)).await;
                self.capture_mouse_position().await
            }
            #[cfg(not(target_os = "windows"))]
            {
                tokio::time::sleep(tokio::time::Duration::from_millis(50)).await;
                self.capture_mouse_position().await
            }
        } else {
            MousePosition { x: 0, y: 0, captured: false }
        };

        (result, position, action)
    }
    
    /// Windows execution by writing to files for AutoHotkey
    #[cfg(target_os = "windows")]
    async fn execute_windows(&self, command: &str) -> Result<String, String> {

        if command.contains("keyboard_cmd.txt") {
            if let Some(content) = command
                .split("echo ")
                .nth(1)
                .and_then(|s| s.split(" > ").next())
            {
                let _ = std::fs::write(r"C:\keyboard_cmd.txt", content);
                return Ok(format!("Executed: {}", content));
            }
        }

        let output = ProcessCommand::new("cmd")
            .arg("/c")
            .arg(command)
            .output()
            .map_err(|e| {
                error!("Failed to execute command: {}", e);
                format!("Execution error: {}", e)
            })?;

        if !output.status.success() {
            let error_msg = String::from_utf8_lossy(&output.stderr).to_string();
            error!("Command failed: {}", error_msg);
            return Err(error_msg);
        }

        debug!("Command executed: {}", command);
        Ok(format!("Executed: {}", command))
    }
    
    /// macOS execution using cliclick
    #[cfg(target_os = "macos")]
    async fn execute_macos(&self, command: &str) -> Result<String, String> {
        // Check if cliclick is available
        if !self.capabilities.contains(&"cliclick".to_string()) {
            return Err("cliclick not available - please install it".to_string());
        }

        // Compound commands (scroll uses cliclick && osascript) must run via sh -c.
        // Pure osascript commands also need shell execution.
        if command.contains("&&") || command.starts_with("osascript") || command.contains("t:\"") {
            let output = ProcessCommand::new("sh")
                .arg("-c")
                .arg(command)
                .output()
                .map_err(|e| format!("Execution error: {}", e))?;

            return if output.status.success() {
                Ok(format!("Executed: {}", command))
            } else {
                Err(String::from_utf8_lossy(&output.stderr).to_string())
            };
        }

        // Try multiple cliclick paths.
        let args: Vec<&str> = command.split_whitespace()
            .filter(|&s| s != "cliclick")
            .collect();

        // Use cached path resolved at startup — no repeated path probing per command
        let cliclick_path = self.cliclick_path.as_deref().unwrap_or("cliclick");

        match ProcessCommand::new(cliclick_path)
            .args(&args)
            .output()
        {
            Ok(output) => {
                if output.status.success() {
                    debug!("Command executed via {}: {}", cliclick_path, command);
                    Ok(format!("Executed: {}", command))
                } else {
                    let err = String::from_utf8_lossy(&output.stderr).to_string();
                    error!("cliclick failed: {}", err);
                    Err(format!("Execution failed: {}", err))
                }
            }
            Err(e) => {
                error!("Failed to execute cliclick: {}", e);
                Err(format!("Execution error: {}", e))
            }
        }
    }
    
    /// Linux execution using xdotool
    #[cfg(target_os = "linux")]
    async fn execute_linux(&self, command: &str) -> Result<String, String> {
        // Check if xdotool is available
        if !self.capabilities.contains(&"xdotool".to_string()) {
            return Err("xdotool not available - please install it".to_string());
        }
        
        let output = ProcessCommand::new("sh")
            .arg("-c")
            .arg(command)
            .output()
            .map_err(|e| {
                error!("Failed to execute command: {}", e);
                format!("Execution error: {}", e)
            })?;
        
        if !output.status.success() {
            let error_msg = String::from_utf8_lossy(&output.stderr).to_string();
            error!("Command failed: {}", error_msg);
            return Err(error_msg);
        }
        
        debug!("Command executed: {}", command);
        Ok(format!("Executed: {}", command))
    }
    
    // Stub implementations for cross-compilation
    #[cfg(not(target_os = "windows"))]
    async fn execute_windows(&self, _command: &str) -> Result<String, String> {
        Err("Windows execution not available on this platform".to_string())
    }
    
    #[cfg(not(target_os = "macos"))]
    async fn execute_macos(&self, _command: &str) -> Result<String, String> {
        Err("macOS execution not available on this platform".to_string())
    }
    
    #[cfg(not(target_os = "linux"))]
    async fn execute_linux(&self, _command: &str) -> Result<String, String> {
        Err("Linux execution not available on this platform".to_string())
    }
}

// Implement the gRPC service
#[tonic::async_trait]
impl AgentService for AgentServiceImpl {
    async fn get_info(
        &self,
        _request: Request<InfoRequest>,
    ) -> Result<Response<AgentInfo>, Status> {
        info!("Agent info requested");
        
        Ok(Response::new(AgentInfo {
            os: self.os_type as i32,
            os_version: self.os_version.clone(),
            capabilities: self.capabilities.clone(),
            agent_version: env!("CARGO_PKG_VERSION").to_string(),
        }))
    }
    
    // Execute with position tracking and detailed messages
    async fn execute(
        &self,
        request: Request<ExecuteRequest>,
    ) -> Result<Response<ExecuteResponse>, Status> {
        let req = request.into_inner();
        
        debug!("Executing command: id={}, cmd={}", req.id, req.command);
        
        let start = Instant::now();
        // execute_command() runs the OS-level command and captures mouse position
        // when the OS string is recognisable as a mouse action (e.g. xdotool/cliclick
        // commands containing "click").  We keep calling it with the raw OS command
        // so execution is unchanged.
        let (result, position, _os_action) = self.execute_command(&req.command).await;
        let execution_time = start.elapsed().as_millis() as i64;
        
        // BUG-008 FIX: derive the human-readable command ("960 540 left") from the
        // raw OS command ("cmd /c echo 960 540 left > C:\mouse_cmd.txt") so that
        // parse_action_details() and build_detailed_message() produce meaningful
        // log entries instead of "Typed: cmd /c echo …".
        let human_cmd = self.extract_human_command(&req.command);
        let human_action = self.parse_action_details(&human_cmd);
        
        match result {
            Ok(_) => {
                // Build detailed message from the HUMAN command, not the OS command
                let message = self.build_detailed_message(&human_action, &position, &human_cmd);
                
                // Single clean log line per command
                if position.captured && human_action.is_mouse {
                    info!(
                        "{{\"action\": \"{}\", \"X\": {}, \"Y\": {}, \"time_taken\": \"{}ms\"}}",
                        message, position.x, position.y, execution_time
                    );
                } else {
                    info!(
                        "{{\"action\": \"{}\", \"time_taken\": \"{}ms\"}}",
                        message, execution_time
                    );
                }
                
                Ok(Response::new(ExecuteResponse {
                    id: req.id,
                    success: true,
                    message,
                    execution_time_ms: execution_time,
                    // Position data
                    mouse_x: if position.captured { Some(position.x) } else { None },
                    mouse_y: if position.captured { Some(position.y) } else { None },
                    position_captured: Some(position.captured),
                }))
            }
            Err(error) => {
                warn!("Command failed: id={}, error={}", req.id, error);
                
                Ok(Response::new(ExecuteResponse {
                    id: req.id,
                    success: false,
                    message: error,
                    execution_time_ms: execution_time,
                    mouse_x: None,
                    mouse_y: None,
                    position_captured: Some(false),
                }))
            }
        }
    }
    
    async fn ping(
        &self,
        _request: Request<PingRequest>,
    ) -> Result<Response<PongResponse>, Status> {
        Ok(Response::new(PongResponse { alive: true }))
    }
}

// Main function to start the agent
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    tracing_subscriber::fmt::init();
    
    info!("Control Center Agent v1.0.0 (WITH POSITION TRACKING)");
    info!("Starting Agent...");
    
    // Create agent service (keeps all execution logic)
    let service = AgentServiceImpl::new();
    let os_type = service.os_type;
    let os_version = service.os_version.clone();
    let capabilities = service.capabilities.clone();
    
    // Read server connection info from environment
    let server_host = std::env::var("AGENT_SERVER_HOST")
        .unwrap_or_else(|_| "127.0.0.1".to_string());
    let server_port = std::env::var("AGENT_SERVER_PORT")
        .unwrap_or_else(|_| "50051".to_string())
        .parse()
        .unwrap_or(50051);
    
    info!("Connecting to server at {}:{}...", server_host, server_port);
    
    // Build agent identity
    let agent_identity = identity::build_agent_identity(
        os_type,
        os_version,
        capabilities,
        env!("CARGO_PKG_VERSION").to_string(),
    );
    
    // Validate identity
    if let Err(e) = identity::validate_agent_identity(&agent_identity) {
        error!("Invalid agent identity: {}", e);
        return Err(e.into());
    }
    
    // Create connection manager
    let auth_token = std::env::var("CONTROL_CENTER_TOKEN").ok();
    let connection_manager = connection::ConnectionManager::new(
        server_host,
        server_port,
        agent_identity,
        auth_token,
    );
    
    // Connect and register
        match connection_manager.connect_and_register().await {
        Ok(mut client) => {
            info!("✓ Ready to accept commands");
            
            let agent_start_time = std::time::Instant::now();
            let commands_executed = std::sync::Arc::new(tokio::sync::RwLock::new(0u64));
            let commands_failed = std::sync::Arc::new(tokio::sync::RwLock::new(0u64));
            let (agent_tx, agent_rx) = tokio::sync::mpsc::channel(100);
            
            // Start bidirectional stream with server
            info!("Starting bidirectional stream with server...");
            let request_stream = tokio_stream::wrappers::ReceiverStream::new(agent_rx);
            
            let response = match client.agent_stream(Request::new(request_stream)).await {
                Ok(resp) => resp,
                Err(e) => {
                    error!("Failed to start agent stream: {}", e);
                    return Err(e.into());
                }
            };
            
            let mut server_stream = response.into_inner();
            info!("✓ Bidirectional stream established");
            
            // Get connection ID for heartbeats
            let connection_id = connection_manager.get_connection_id().await
                .ok_or_else(|| {
                    error!("No connection ID available");
                    "No connection ID"
                })?;
            
            // Spawn heartbeat sender with REAL metrics
            let heartbeat_tx = agent_tx.clone();
            let heartbeat_conn_id = connection_id.clone();
            let heartbeat_start_time = agent_start_time;
            let heartbeat_executed = commands_executed.clone();
            let heartbeat_failed = commands_failed.clone();
            
            tokio::spawn(async move {
                let mut interval = tokio::time::interval(tokio::time::Duration::from_secs(30));
                loop {
                    interval.tick().await;
                    
                    // Calculate REAL uptime
                    let uptime_seconds = heartbeat_start_time.elapsed().as_secs();
                    
                    // Get REAL command counts
                    let executed = *heartbeat_executed.read().await;
                    let failed = *heartbeat_failed.read().await;
                    
                    let heartbeat = proto::AgentHeartbeat {
                        connection_id: heartbeat_conn_id.clone(),
                        timestamp: chrono::Utc::now().timestamp(),
                        status: Some(proto::AgentStatus {
                            ready: true,
                            commands_executed: executed,
                            commands_failed: failed,
                            uptime_seconds: uptime_seconds as i64,
                            system_info: std::collections::HashMap::new(),
                        }),
                        current_command_id: None,
                    };
                    
                    let agent_msg = proto::AgentMessage {
                        connection_id: heartbeat_conn_id.clone(),
                        payload: Some(proto::agent_message::Payload::Heartbeat(heartbeat)),
                    };
                    
                    if heartbeat_tx.send(agent_msg).await.is_err() {
                        warn!("Failed to send heartbeat, stream may be closed");
                        break;
                    }
                    
                    debug!(
                        "Sent heartbeat - uptime: {}s, executed: {}, failed: {}",
                        uptime_seconds, executed, failed
                    );
                }
            });
            
            info!("Agent running. Press Ctrl+C to stop.");
            info!("Listening for commands from server...");
            info!("Full tracking enabled (commands, uptime, execution times)");
            
            // Main command loop - listen for messages from server
            loop {
                tokio::select! {
                    // Handle Ctrl+C
                    _ = tokio::signal::ctrl_c() => {
                        info!("Received Ctrl+C, shutting down...");
                        
                        // Send disconnect message
                        let disconnect = proto::DisconnectNotice {
                            reason: "User requested shutdown".to_string(),
                            timestamp: chrono::Utc::now().timestamp(),
                            graceful: true,
                        };
                        
                        let agent_msg = proto::AgentMessage {
                            connection_id: connection_id.clone(),
                            payload: Some(proto::agent_message::Payload::Disconnect(disconnect)),
                        };
                        
                        let _ = agent_tx.send(agent_msg).await;
                        
                        break;
                    }
                    
                    // Handle incoming messages from server
                    server_msg = server_stream.message() => {
                        match server_msg {
                            Ok(Some(msg)) => {
                                match msg.payload {
                                    Some(proto::server_message::Payload::CommandRequest(cmd_req)) => {
                                        let command_id = cmd_req.id.clone();
                                        let command = cmd_req.command.clone();
                                        
                                        // Track command execution time
                                        let cmd_start_time = std::time::Instant::now();
                                        
                                        debug!("Received command: {} (ID: {})", command, command_id);
                                        
                                        // Execute command using AgentServiceImpl
                                        let execute_request = proto::ExecuteRequest {
                                            id: command_id.clone(),
                                            command: command.clone(),
                                            user_id: cmd_req.user_id.clone(),
                                        };
                                        
                                        let result = service.execute(Request::new(execute_request)).await;
                                        
                                        // Calculate execution time
                                        let execution_time = cmd_start_time.elapsed();
                                        
                                        // Build response and update counters
                                        let response = match result {
                                            Ok(resp) => {
                                                let exec_resp = resp.into_inner();
                                                
                                                // Increment success counter
                                                *commands_executed.write().await += 1;
                                                
                                                debug!(
                                                    "Command {} executed successfully (time: {:?})",
                                                    command_id,
                                                    execution_time
                                                );
                                                
                                                proto::CommandResponse {
                                                    id: command_id.clone(),
                                                    success: exec_resp.success,
                                                    message: exec_resp.message,
                                                    execution_time_ms: exec_resp.execution_time_ms,
                                                    mouse_x: exec_resp.mouse_x,
                                                    mouse_y: exec_resp.mouse_y,
                                                    position_captured: exec_resp.position_captured,
                                                    metadata: std::collections::HashMap::new(),
                                                }
                                            }
                                            Err(e) => {
                                                // Increment failure counter
                                                *commands_failed.write().await += 1;
                                                
                                                error!(
                                                    "Command {} failed: {} (time: {:?})",
                                                    command_id,
                                                    e,
                                                    execution_time
                                                );
                                                
                                                proto::CommandResponse {
                                                    id: command_id.clone(),
                                                    success: false,
                                                    message: format!("Execution error: {}", e),
                                                    execution_time_ms: execution_time.as_millis() as i64,
                                                    mouse_x: None,
                                                    mouse_y: None,
                                                    position_captured: None,
                                                    metadata: std::collections::HashMap::new(),
                                                }
                                            }
                                        };
                                        
                                        // Send response back to server
                                        let agent_msg = proto::AgentMessage {
                                            connection_id: connection_id.clone(),
                                            payload: Some(proto::agent_message::Payload::CommandResponse(response)),
                                        };
                                        
                                        if agent_tx.send(agent_msg).await.is_err() {
                                            error!("Failed to send command response, stream closed");
                                            break;
                                        }
                                        
                                        debug!("Sent command response for {}", command_id);
                                    }
                                    
                                    Some(proto::server_message::Payload::Heartbeat(_heartbeat)) => {
                                        debug!("Received heartbeat from server");
                                        // Server is alive, no action needed
                                    }
                                    
                                    Some(proto::server_message::Payload::Disconnect(notice)) => {
                                        warn!("Server requested disconnect: {}", notice.reason);
                                        break;
                                    }
                                    
                                    Some(proto::server_message::Payload::ConfigUpdate(config)) => {
                                        debug!("Received config update from server");
                                        // Log the settings being updated
                                        for (key, value) in config.settings.iter() {
                                            debug!("Config update: {} = {}", key, value);
                                        }
                                        // Config updates can be implemented in the future if needed
                                    }
                                    
                                    None => {
                                        warn!("Received message with no payload");
                                    }
                                }
                            }
                            Ok(None) => {
                                info!("Server closed stream");
                                break;
                            }
                            Err(e) => {
                                error!("Stream error: {}", e);
                                break;
                            }
                        }
                    }
                }
            }
            
            // Print final statistics on shutdown
            let final_executed = *commands_executed.read().await;
            let final_failed = *commands_failed.read().await;
            let final_uptime = agent_start_time.elapsed();
            
            info!("═══════════════════════════════════════");
            info!("Agent Shutdown Statistics");
            info!("═══════════════════════════════════════");
            info!("  Uptime: {:.2}h ({:.0}s)", 
                final_uptime.as_secs_f64() / 3600.0,
                final_uptime.as_secs_f64());
            info!("  Commands executed: {}", final_executed);
            info!("  Commands failed: {}", final_failed);
            info!("  Success rate: {:.2}%", 
                if final_executed + final_failed > 0 {
                    (final_executed as f64 / (final_executed + final_failed) as f64) * 100.0
                } else {
                    0.0
                });
            info!("═══════════════════════════════════════");
        }
        Err(e) => {
            error!("Failed to connect: {}", e);
            return Err(e);
        }
    }
    
    Ok(())
}

// Unit tests for OS detection and command validation
#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_os_detection() {
        let (_os_type, version) = AgentServiceImpl::detect_os_version();
        assert!(!version.is_empty());
        assert!(!version.contains("Unknown") || cfg!(debug_assertions));
    }
    
    #[test]
    fn test_command_validation() {
        let agent = AgentServiceImpl::new();
        
        // Valid commands
        assert!(agent.validate_command("960 540 left").is_ok());
        assert!(agent.validate_command("type Hello World").is_ok());
        
        // Invalid commands
        assert!(agent.validate_command("").is_err());
        assert!(agent.validate_command("rm -rf /").is_err());
        assert!(agent.validate_command(&"x".repeat(10001)).is_err());
    }
}