// crates/agent/src/main.rs

use tonic::{Request, Response, Status};
use tracing::{info, warn, error, debug};
use std::process::Command as ProcessCommand;
use std::collections::HashMap;
use std::sync::Arc;
use tokio::sync::RwLock;
#[cfg(any(target_os = "linux"))]
use regex::Regex;

// Protobuf definitions generated by tonic
mod proto {
    tonic::include_proto!("control_center");
}

mod argv_policy;
mod identity;
mod connection;

// Re-exporting for easier access
use proto::{
    agent_service_server::AgentService,
};

// For cross-platform OS detection
use proto::{
    AgentInfo,
    ExecuteRequest, 
    ExecuteResponse,
    InfoRequest,
    PingRequest, 
    PongResponse,
    OsType,
};

/// Re-reads allowed when the cursor readback disagrees with the requested position,
/// and the pause between them. Bounded because the agent serves one command at a
/// time — an unbounded settle loop would stall all actuation on a display where the
/// cursor never reaches the requested point.
const MAX_POSITION_REREADS: u32 = 3;
const POSITION_REREAD_INTERVAL_MS: u64 = 50;

// Mouse position data structure
#[derive(Debug, Clone)]
struct MousePosition {
    x: i32,
    y: i32,
    captured: bool,
}

/// A mouse button the agent has pressed and not yet released.
///
/// `X Y hold` issues a button-down with no timeout. Without this, an unmatched hold
/// leaves the button physically down: every later click or move is interpreted as a
/// drag-select, and the console reports plain success throughout.
#[derive(Debug, Clone)]
struct HeldButton {
    /// Where the button went down, when the command named a coordinate.
    ///
    /// `here hold` names none. Substituting (0, 0) for "unknown" would make the
    /// automatic release move the cursor to the top-left corner first — dragging
    /// whatever is grabbed to the origin on the way out, which is worse than the
    /// stuck button it is meant to fix. Unknown releases in place instead.
    at: Option<(i32, i32)>,
    since: std::time::Instant,
}

// Detailed action information
#[derive(Debug, Clone)]
struct ActionDetails {
    action_type: String,  // "left", "right", "double", "drag", etc.
    is_mouse: bool,
    is_here_command: bool,
}

/// Agent implementation
pub struct AgentServiceImpl {
    os_type: OsType,
    os_version: String,
    capabilities: Vec<String>,
    #[cfg(target_os = "macos")]
    cliclick_path: Option<String>,
    /// Buttons pressed and not yet released, keyed by button name. Populated from
    /// the validated argv, never from the caller-supplied human_command, because it
    /// drives an automatic release at shutdown.
    held_buttons: Arc<RwLock<HashMap<String, HeldButton>>>,
}

/// Core implementation of the AgentService
impl AgentServiceImpl {
    pub fn new() -> Self {
        let (os_type, os_version) = Self::detect_os_version();
        let capabilities = Self::detect_capabilities(&os_type);
        
        info!("Agent initialized with position tracking");
        info!("  OS: {:?}", os_type);
        info!("  Version: {}", os_version);
        info!("  Capabilities: {:?}", capabilities);
        
        Self {
            os_type,
            os_version,
            capabilities,
            #[cfg(target_os = "macos")]
            cliclick_path: Self::resolve_cliclick_path(),
            held_buttons: Arc::new(RwLock::new(HashMap::new())),
        }
    }

    #[cfg(target_os = "macos")]
    fn resolve_cliclick_path() -> Option<String> {
        let paths = [
            "/usr/local/bin/cliclick",
            "/opt/homebrew/bin/cliclick",
            "cliclick",
        ];
        for p in &paths {
            if ProcessCommand::new(p).arg("--version").output().is_ok() {
                return Some(p.to_string());
            }
        }
        None
    }
    
    /// Real OS detection with version information
    fn detect_os_version() -> (OsType, String) {
        #[cfg(target_os = "windows")]
        {
            Self::detect_windows_version()
        }
        
        #[cfg(target_os = "macos")]
        {
            Self::detect_macos_version()
        }
        
        #[cfg(target_os = "linux")]
        {
            Self::detect_linux_version()
        }
    }
    
    /// Windows version detection using registry
    #[cfg(target_os = "windows")]
    fn detect_windows_version() -> (OsType, String) {
        use winreg::enums::*;
        use winreg::RegKey;
        
        let hklm = RegKey::predef(HKEY_LOCAL_MACHINE);
        
        if let Ok(current_version) = hklm.open_subkey("SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion") {
            let product_name: String = current_version.get_value("ProductName").unwrap_or_else(|_| "Windows".to_string());
            let display_version: String = current_version.get_value("DisplayVersion").unwrap_or_else(|_| String::new());
            let current_build: String = current_version.get_value("CurrentBuild").unwrap_or_else(|_| String::new());
            
            let version = if !display_version.is_empty() && !current_build.is_empty() {
                format!("{} {} (Build {})", product_name, display_version, current_build)
            } else if !current_build.is_empty() {
                format!("{} (Build {})", product_name, current_build)
            } else {
                product_name
            };
            
            return (OsType::Windows, version);
        }
        
        (OsType::Windows, "Windows (Unknown Version)".to_string())
    }
    
    /// Linux version detection using /etc/os-release and fallback methods
    #[cfg(target_os = "linux")]
    fn detect_linux_version() -> (OsType, String) {
        use std::fs;
        // Try /etc/os-release first (systemd standard)
        if let Ok(content) = fs::read_to_string("/etc/os-release") {
            let mut pretty_name = None;
            
            for line in content.lines() {
                if line.starts_with("PRETTY_NAME=") {
                    pretty_name = Some(
                        line.split('=')
                            .nth(1)
                            .unwrap_or("")
                            .trim_matches('"')
                            .to_string()
                    );
                    break;
                }
            }
            
            if let Some(name) = pretty_name {
                return (OsType::Linux, name);
            }
        }
        
        // Fallback: try lsb_release command
        if let Ok(output) = ProcessCommand::new("lsb_release").arg("-d").output() {
            if let Ok(description) = String::from_utf8(output.stdout) {
                if let Some(version) = description.split(':').nth(1) {
                    return (OsType::Linux, version.trim().to_string());
                }
            }
        }
        
        // Last resort: try uname
        if let Ok(output) = ProcessCommand::new("uname").arg("-sr").output() {
            if let Ok(version) = String::from_utf8(output.stdout) {
                return (OsType::Linux, version.trim().to_string());
            }
        }
        
        (OsType::Linux, "Linux (Unknown Distribution)".to_string())
    }
    
    /// macOS version detection using sw_vers
    #[cfg(target_os = "macos")]
    fn detect_macos_version() -> (OsType, String) {
        // Get macOS version using sw_vers
        if let Ok(output) = ProcessCommand::new("sw_vers").arg("-productVersion").output() {
            if let Ok(version) = String::from_utf8(output.stdout) {
                let version = version.trim();
                
                // Get build number
                if let Ok(build_output) = ProcessCommand::new("sw_vers").arg("-buildVersion").output() {
                    if let Ok(build) = String::from_utf8(build_output.stdout) {
                        return (
                            OsType::Macos,
                            format!("macOS {} (Build {})", version, build.trim())
                        );
                    }
                }
                
                return (OsType::Macos, format!("macOS {}", version));
            }
        }
        
        (OsType::Macos, "macOS (Unknown Version)".to_string())
    }
    
    /// Detect available capabilities
    fn detect_capabilities(os_type: &OsType) -> Vec<String> {
        let mut capabilities = vec!["mouse".to_string(), "keyboard".to_string(), "position_tracking".to_string()];
        
        match os_type {
            OsType::Windows => {
                capabilities.push("file_based_control".to_string());
            }
            OsType::Macos => {
                // Check if cliclick is available
                if ProcessCommand::new("which").arg("cliclick").output().is_ok() {
                    capabilities.push("cliclick".to_string());
                } else {
                    warn!("cliclick not found - install with: brew install cliclick");
                }
            }
            OsType::Linux => {
                // Check if xdotool is available
                if ProcessCommand::new("which").arg("xdotool").output().is_ok() {
                    capabilities.push("xdotool".to_string());
                } else {
                    warn!("xdotool not found - install with: sudo apt-get install xdotool");
                }
            }
        }
        
        capabilities
    }
    
    // Convert a key string with modifiers into a human-readable format
    fn format_keys_for_display(&self, keys: &str) -> String {
        let mod_names: &[(&str, &str)] = match self.os_type {
            OsType::Macos   => &[("#", "Cmd"),   ("!", "Option"), ("^", "Ctrl"), ("+", "Shift")],
            OsType::Windows => &[("#", "Win"),   ("!", "Alt"),    ("^", "Ctrl"), ("+", "Shift")],
            OsType::Linux   => &[("#", "Super"), ("!", "Alt"),    ("^", "Ctrl"), ("+", "Shift")],
        };

        let special_name = |k: &str| -> Option<&'static str> {
            match k {
                "{Enter}" | "{Return}" => Some("Return"),
                "{Tab}"                => Some("Tab"),
                "{Esc}" | "{Escape}"   => Some("Esc"),
                "{Backspace}" | "{BS}" => Some("Delete"),
                "{Delete}" | "{Del}"   => Some("Fwd Delete"),
                "{Space}"              => Some("Space"),
                "{Up}"                 => Some("Up"),
                "{Down}"               => Some("Down"),
                "{Left}"               => Some("Left"),
                "{Right}"              => Some("Right"),
                "{Home}"               => Some("Home"),
                "{End}"                => Some("End"),
                "{PgUp}"               => Some("Page Up"),
                "{PgDn}"               => Some("Page Down"),
                "{F1}"  => Some("F1"),  "{F2}"  => Some("F2"),
                "{F3}"  => Some("F3"),  "{F4}"  => Some("F4"),
                "{F5}"  => Some("F5"),  "{F6}"  => Some("F6"),
                "{F7}"  => Some("F7"),  "{F8}"  => Some("F8"),
                "{F9}"  => Some("F9"),  "{F10}" => Some("F10"),
                "{F11}" => Some("F11"), "{F12}" => Some("F12"),
                _       => None,
            }
        };

        // Fast path: whole string is a bare special key
        if let Some(name) = special_name(keys) {
            return name.to_string();
        }

        let modifier_syms: &[char] = &['#', '!', '^', '+'];
        let mut parts: Vec<String> = Vec::new();
        let mut byte_pos = 0usize;

        for ch in keys.chars() {
            if !modifier_syms.contains(&ch) { break; }
            let sym = &keys[byte_pos..byte_pos + ch.len_utf8()];
            if let Some((_, name)) = mod_names.iter().find(|(s, _)| *s == sym) {
                parts.push(name.to_string());
            }
            byte_pos += ch.len_utf8();
        }

        let key_part = &keys[byte_pos..];
        if !key_part.is_empty() {
            if let Some(name) = special_name(key_part) {
                parts.push(name.to_string());
            } else if let Some(code) = key_part
                .strip_prefix("{code:")
                .and_then(|c| c.strip_suffix('}'))
                .filter(|c| c.chars().all(|ch| ch.is_ascii_digit()) && !c.is_empty())
            {
                // Keycode passthrough. Rendering the raw "code:21" here would put it
                // in the recorded step text, so give it a readable name.
                parts.push(format!("Key {}", code));
            } else if key_part.starts_with('{') && key_part.ends_with('}') {
                parts.push(key_part[1..key_part.len() - 1].to_string());
            } else if key_part.chars().count() == 1 {
                parts.push(key_part.to_uppercase());
            } else {
                parts.push(key_part.to_string());
            }
        }

        if parts.is_empty() { keys.to_string() } else { parts.join("+") }
    }

    fn parse_action_details(&self, command: &str) -> ActionDetails {
        let tokens: Vec<&str> = command.split_whitespace().collect();

        let is_here = tokens.get(0) == Some(&"here");

        let action_type = if tokens.len() >= 3 && tokens[0].parse::<i32>().is_ok() {
            // Coordinate-based: "960 540 left"
            tokens.get(2).unwrap_or(&"move").to_string()
        } else if is_here && tokens.len() >= 2 {
            // Here command: "here left", "here hold", "here release"
            tokens[1].to_string()
        } else if tokens.get(0) == Some(&"position") {
            "position".to_string()
        } else if tokens.get(0) == Some(&"press") {
            // "press {Enter}", "press ^c" — keyboard, not mouse
            "press".to_string()
        } else if command.contains("click") {
            "click".to_string()
        } else if command.contains("drag") {
            "drag".to_string()
        } else if command.contains("type") || command.contains("key") {
            "keyboard".to_string()
        } else {
            "unknown".to_string()
        };

        let is_mouse = matches!(
            action_type.as_str(),
            "left" | "right" | "middle" | "double" | "triple"
            | "click" | "drag" | "move"
            | "scroll_up" | "scroll_down"
            | "hold" | "release"     // mouse button hold/release
            | "position"             // position query
        );

        ActionDetails {
            action_type,
            is_mouse,
            is_here_command: is_here,
        }
    }
    
    // Capture mouse position after execution
    async fn capture_mouse_position(&self) -> MousePosition {
        match self.os_type {
            OsType::Linux => self.capture_position_linux().await,
            OsType::Windows => self.capture_position_windows().await,
            OsType::Macos => self.capture_position_macos().await,
        }
    }
    
    #[cfg(target_os = "linux")]
    async fn capture_position_linux(&self) -> MousePosition {
        // Direct spawn with DISPLAY supplied via the environment. The agent invokes no
        // shell anywhere, so there is no interpreter for any input to reach.
        let display = std::env::var("DISPLAY").unwrap_or_else(|_| ":0".to_string());
        match ProcessCommand::new("xdotool")
            .args(["getmouselocation", "--shell"])
            .env("DISPLAY", display)
            .output()
        {
            Ok(output) if output.status.success() => {
                let stdout = String::from_utf8_lossy(&output.stdout);
                let x_regex = Regex::new(r"X=(\d+)").unwrap();
                let y_regex = Regex::new(r"Y=(\d+)").unwrap();
                
                if let (Some(x_cap), Some(y_cap)) = (x_regex.captures(&stdout), y_regex.captures(&stdout)) {
                    if let (Ok(x), Ok(y)) = (x_cap[1].parse::<i32>(), y_cap[1].parse::<i32>()) {
                        debug!("Position captured: ({}, {})", x, y);
                        return MousePosition { x, y, captured: true };
                    }
                }
            }
            _ => {}
        }
        MousePosition { x: 0, y: 0, captured: false }
    }
    
    #[cfg(target_os = "windows")]
    async fn capture_position_windows(&self) -> MousePosition {
        use winreg::enums::{HKEY_CURRENT_USER, KEY_READ};
        use winreg::RegKey;

        let hkcu = RegKey::predef(HKEY_CURRENT_USER);
        if let Ok(key) = hkcu.open_subkey_with_flags("Software\\MouseTracker", KEY_READ) {
            if let (Ok(x_str), Ok(y_str)) = (
                key.get_value::<String, _>("MouseX"),
                key.get_value::<String, _>("MouseY"),
            ) {
                if let (Ok(x), Ok(y)) = (x_str.parse::<i32>(), y_str.parse::<i32>()) {
                    debug!("Position captured from registry: ({}, {})", x, y);
                    return MousePosition { x, y, captured: true };
                }
            }
        }

        MousePosition { x: 0, y: 0, captured: false }
    }
    
    #[cfg(target_os = "macos")]
    async fn capture_position_macos(&self) -> MousePosition {
        let cliclick_paths = ["/usr/local/bin/cliclick", "/opt/homebrew/bin/cliclick", "cliclick"];
        
        for cliclick_path in &cliclick_paths {
            if let Ok(output) = ProcessCommand::new(cliclick_path).arg("p:.").output() {
                if output.status.success() {
                    let stdout = String::from_utf8_lossy(&output.stdout).trim().to_string();
                    let parts: Vec<&str> = stdout.split(',').collect();
                    
                    if parts.len() == 2 {
                        if let (Ok(x), Ok(y)) = (parts[0].parse::<i32>(), parts[1].parse::<i32>()) {
                            debug!("Position captured: ({}, {})", x, y);
                            return MousePosition { x, y, captured: true };
                        }
                    }
                }
            }
        }
        MousePosition { x: 0, y: 0, captured: false }
    }
    
    // Cross-compilation stubs
    #[cfg(not(target_os = "linux"))]
    async fn capture_position_linux(&self) -> MousePosition {
        MousePosition { x: 0, y: 0, captured: false }
    }
    
    #[cfg(not(target_os = "windows"))]
    async fn capture_position_windows(&self) -> MousePosition {
        MousePosition { x: 0, y: 0, captured: false }
    }
    
    #[cfg(not(target_os = "macos"))]
    async fn capture_position_macos(&self) -> MousePosition {
        MousePosition { x: 0, y: 0, captured: false }
    }
    
    // Build detailed message with action and position
    fn build_detailed_message(
        &self,
        action: &ActionDetails,
        position: &MousePosition,
        command: &str,
    ) -> String {
        // Keyboard actions
        if action.action_type == "press" {
            let keys = command.trim_start_matches("press").trim();
            return format!("Pressed: {}", self.format_keys_for_display(keys));
        }
        if action.action_type == "keyboard" {
            // "type x.ai/careers" → "Typed: x.ai/careers"
            let content = command.trim_start_matches("type").trim();
            return format!("Typed: {}", content);
        }
        if !action.is_mouse {
            return format!("Typed: {}", command);
        }

        // Position query
        if action.action_type == "position" {
            return if position.captured {
                format!("Position: X={}, Y={}", position.x, position.y)
            } else {
                "Position: (?, ?)".to_string()
            };
        }

        // Mouse actions that don't need position
        if !position.captured {
            return format!("Executed: {}", command);
        }

        // Mouse actions with position
        let action_name = match action.action_type.as_str() {
            "left"         => "Left-clicked",
            "right"        => "Right-clicked",
            "middle"       => "Middle-clicked",
            "double"       => "Double-clicked",
            "triple"       => "Triple-clicked",
            "drag"         => "Dragged",
            "move"         => "Moved cursor to",
            "scroll_up"    => "Scrolled up at",
            "scroll_down"  => "Scrolled down at",
            "hold"         => "Held button at",
            "release"      => "Released button at",
            _              => "Performed action at",
        };

        if action.is_here_command {
            format!("{} at X={}, Y={}", action_name, position.x, position.y)
        } else if action.action_type == "drag" {
            let tokens: Vec<&str> = command.split_whitespace().collect();
            if tokens.len() >= 5 {
                if let (Ok(x1), Ok(y1), Ok(x2), Ok(y2)) = (
                    tokens[0].parse::<i32>(),
                    tokens[1].parse::<i32>(),
                    tokens[3].parse::<i32>(),
                    tokens[4].parse::<i32>(),
                ) {
                    return format!("Dragged from X={}, Y={} to X={}, Y={}", x1, y1, x2, y2);
                }
            }
            format!("Dragged to X={}, Y={}", position.x, position.y)
        } else {
            format!("{} at X={}, Y={}", action_name, position.x, position.y)
        }
    }
    
    // Capture mouse position after a successful mouse action, verifying it against
    // the position the command asked for.
    //
    // A bare readback is not evidence. It can return the position from before the
    // command (the read raced the synthetic event) or the position the cursor never
    // left (the warp silently failed — reproducible on an X display with no mapped
    // window, where xdotool exits 0 and moves nothing). Either way the old code
    // reported `captured: true`, and that one value is both the operator's
    // step-gating signal and the coordinate stored in the training corpus.
    //
    // So: read, compare against the request, and re-read a bounded number of times
    // before giving up. Never report a coordinate that disagrees with the command —
    // `position_captured: false` is the honest answer and the schema already carries
    // it. The loop is capped because the agent serves one command at a time.
    async fn capture_position_if_mouse(
        &self,
        action: &ActionDetails,
        ok: bool,
        expected: Option<argv_policy::ExpectedPos>,
        before: Option<MousePosition>,
    ) -> MousePosition {
        if !(action.is_mouse && ok) {
            return MousePosition { x: 0, y: 0, captured: false };
        }

        #[cfg(target_os = "windows")]
        let settle_ms = if action.is_here_command { 10 } else { 20 };
        #[cfg(not(target_os = "windows"))]
        let settle_ms = 50;

        tokio::time::sleep(tokio::time::Duration::from_millis(settle_ms)).await;
        let mut position = self.capture_mouse_position().await;

        // Commands that name no coordinate — "here left", "here hold", "position" —
        // do not move the cursor. That invariant is what they can be checked against:
        // a read taken before the command and one taken after must agree. If they do
        // not, something moved the cursor across the sample and neither value
        // describes the action, so report nothing rather than pick one.
        //
        // Without this these commands kept the old behaviour of publishing whatever
        // the readback returned as `captured: true` — the same unverified report the
        // coordinate path was fixed for, and `position` is exactly the command an
        // operator runs to obtain coordinates for the next step.
        let Some(want) = expected else {
            let Some(before) = before.filter(|p| p.captured) else {
                // No usable pre-read (the readback tool itself is failing). Nothing
                // to verify against, so do not claim a capture.
                return MousePosition { x: 0, y: 0, captured: false };
            };
            for _ in 0..MAX_POSITION_REREADS {
                if position.captured && position.x == before.x && position.y == before.y {
                    return position;
                }
                tokio::time::sleep(tokio::time::Duration::from_millis(
                    POSITION_REREAD_INTERVAL_MS,
                ))
                .await;
                position = self.capture_mouse_position().await;
            }
            if position.captured && position.x == before.x && position.y == before.y {
                return position;
            }
            warn!(
                "Cursor moved across a command that should not move it ({} at ({}, {}) \
                 before, {} after). Reporting position_captured=false.",
                action.action_type,
                before.x,
                before.y,
                if position.captured {
                    format!("({}, {})", position.x, position.y)
                } else {
                    "no read".to_string()
                }
            );
            return MousePosition { x: 0, y: 0, captured: false };
        };

        for attempt in 0..MAX_POSITION_REREADS {
            if position.captured && position.x == want.x && position.y == want.y {
                return position;
            }
            debug!(
                "Position readback {:?} != requested ({}, {}), re-read {}/{}",
                (position.x, position.y), want.x, want.y, attempt + 1, MAX_POSITION_REREADS
            );
            tokio::time::sleep(tokio::time::Duration::from_millis(
                POSITION_REREAD_INTERVAL_MS,
            ))
            .await;
            position = self.capture_mouse_position().await;
        }

        if position.captured && position.x == want.x && position.y == want.y {
            return position;
        }

        warn!(
            "Position readback did not settle: requested ({}, {}), last read {}. \
             Reporting position_captured=false rather than a coordinate that was not verified.",
            want.x,
            want.y,
            if position.captured {
                format!("({}, {})", position.x, position.y)
            } else {
                "none".to_string()
            }
        );
        MousePosition { x: 0, y: 0, captured: false }
    }

    // Execute a structured argv command directly — no shell, so typed text can never
    // be interpreted as shell syntax (F5). `human_command` drives action parsing and
    // the recorded string.
    async fn execute_command_argv(
        &self,
        argv: &[String],
        human_command: &str,
    ) -> (Result<String, String>, MousePosition, ActionDetails) {
        let action = self.parse_action_details(human_command);

        // Validate once and keep the plan: the expected end position and any button
        // transition are read from it, so neither can disagree with the grammar
        // about what a token meant.
        let plan = match argv_policy::validate(argv) {
            Ok(plan) => plan,
            Err(e) => {
                warn!("Blocked command {:?}: {}", argv, e);
                return (
                    Err(e),
                    MousePosition { x: 0, y: 0, captured: false },
                    action,
                );
            }
        };
        let expected = plan.expected_pos();
        let transition = plan.button_transition();

        // A command that names no coordinate is verified against the cursor not
        // having moved, so the "before" sample has to be taken before it runs.
        let before = if action.is_mouse && expected.is_none() {
            Some(self.capture_mouse_position().await)
        } else {
            None
        };

        let result = self.run_plan(plan).await;
        if result.is_ok() {
            self.record_button_transition(transition, expected).await;
        }
        let position = self
            .capture_position_if_mouse(&action, result.is_ok(), expected, before)
            .await;
        (result, position, action)
    }

    // Update the held-button tracker after a command executed successfully.
    async fn record_button_transition(
        &self,
        transition: Option<argv_policy::ButtonTransition>,
        at: Option<argv_policy::ExpectedPos>,
    ) {
        let Some(transition) = transition else { return };
        let name = transition.button.as_str().to_string();
        let mut held = self.held_buttons.write().await;
        if transition.down {
            let at = at.map(|p| (p.x, p.y));
            held.insert(
                name.clone(),
                HeldButton { at, since: std::time::Instant::now() },
            );
            debug!("Tracking held {} button at {:?}", name, at);
        } else {
            held.remove(&name);
        }
    }

    // Render outstanding holds for the response metadata: "left@900,700:7".
    async fn held_buttons_summary(&self) -> String {
        let held = self.held_buttons.read().await;
        let mut entries: Vec<String> = held
            .iter()
            .map(|(name, b)| {
                let at = match b.at {
                    Some((x, y)) => format!("{},{}", x, y),
                    None => "?".to_string(),
                };
                format!("{}@{}:{}", name, at, b.since.elapsed().as_secs())
            })
            .collect();
        entries.sort();
        entries.join(";")
    }

    // The argv that releases a button on this platform. Goes back through the
    // grammar like any other action, so the shutdown path is not a way around it.
    //
    // With no recorded coordinate the release happens where the cursor already is.
    // Both the macOS and Windows forms move before releasing, so substituting an
    // origin would drag whatever is held to the corner.
    fn release_argv(button: argv_policy::MouseButton, at: Option<(i32, i32)>) -> Vec<String> {
        if cfg!(target_os = "macos") {
            let target = match at {
                Some((x, y)) => format!("du:{},{}", x, y),
                None => "du:.".to_string(),
            };
            vec!["cliclick".to_string(), target]
        } else if cfg!(target_os = "windows") {
            let content = match at {
                Some((x, y)) => format!("{} {} release", x, y),
                None => "here release".to_string(),
            };
            vec![
                "__write__".to_string(),
                r"C:\mouse_cmd.txt".to_string(),
                content,
            ]
        } else {
            let n = match button {
                argv_policy::MouseButton::Left => "1",
                argv_policy::MouseButton::Middle => "2",
                argv_policy::MouseButton::Right => "3",
            };
            vec!["xdotool".to_string(), "mouseup".to_string(), n.to_string()]
        }
    }

    // Release every tracked button. Called on every agent-exit path.
    //
    // This is the one place the agent actuates without being asked. It releases only
    // buttons it recorded going down, and it cannot be recorded as a step: by the
    // time it runs the command stream is closed. That is a deliberate trade — a
    // button left physically down corrupts every step of whatever runs next, while
    // an unrecorded release happens after the session has already ended — so it is
    // logged loudly instead.
    async fn release_held_buttons(&self) {
        let outstanding: Vec<(String, HeldButton)> = {
            let held = self.held_buttons.read().await;
            held.iter().map(|(k, v)| (k.clone(), v.clone())).collect()
        };
        if outstanding.is_empty() {
            return;
        }

        for (name, button) in outstanding {
            let kind = match name.as_str() {
                "middle" => argv_policy::MouseButton::Middle,
                "right" => argv_policy::MouseButton::Right,
                _ => argv_policy::MouseButton::Left,
            };
            let argv = Self::release_argv(kind, button.at);
            let outcome = self.run_argv(&argv).await;
            warn!(
                "Auto-released {} button held at {} for {}s during shutdown \
                 ({}). This release is NOT recorded — the command stream is closed.",
                name,
                match button.at {
                    Some((x, y)) => format!("({}, {})", x, y),
                    None => "the current position".to_string(),
                },
                button.since.elapsed().as_secs(),
                match &outcome {
                    Ok(_) => "ok".to_string(),
                    Err(e) => format!("failed: {}", e),
                }
            );
        }
        self.held_buttons.write().await.clear();
    }

    // Run an argv vector directly (no shell). The vector is first checked against the
    // actuation grammar in argv_policy, which constrains sub-commands and arguments —
    // an argv[0] allow-list alone would still permit `xdotool exec` and free-form
    // `osascript -e`. Used by paths that have not already validated, such as the
    // shutdown auto-release.
    async fn run_argv(&self, argv: &[String]) -> Result<String, String> {
        let plan = argv_policy::validate(argv).inspect_err(|e| {
            warn!("Blocked command {:?}: {}", argv, e);
        })?;
        self.run_plan(plan).await
    }

    // Execute an already-validated plan.
    async fn run_plan(&self, plan: argv_policy::Plan) -> Result<String, String> {
        match plan {
            // Windows AutoHotkey file-drop: write content directly, no `cmd /c echo`.
            argv_policy::Plan::Write { path, content } => {
                std::fs::write(&path, &content).map_err(|e| format!("Write error: {}", e))?;
                Ok(format!("Executed: {}", content))
            }
            argv_policy::Plan::Run { bin, args } => {
                self.spawn_actuation(bin, &args)?;
                Ok("ok".to_string())
            }
            // Focus click, then an AppleScript key-repeat loop. Both scripts are
            // composed here, so the client only ever supplies the bounded parameters.
            argv_policy::Plan::Scroll {
                click,
                key_code,
                amount,
            } => {
                self.spawn_actuation(
                    argv_policy::Bin::Cliclick,
                    &[click, "w:50".to_string()],
                )?;
                self.spawn_actuation(
                    argv_policy::Bin::Osascript,
                    &[
                        "-e".to_string(),
                        format!("tell application \"System Events\" to repeat {} times", amount),
                        "-e".to_string(),
                        format!("key code {}", key_code),
                        "-e".to_string(),
                        "delay 0.02".to_string(),
                        "-e".to_string(),
                        "end repeat".to_string(),
                    ],
                )?;
                Ok("ok".to_string())
            }
        }
    }

    // Spawn a validated actuation binary. Never goes through a shell.
    fn spawn_actuation(&self, bin: argv_policy::Bin, args: &[String]) -> Result<(), String> {
        let program: String = match bin {
            argv_policy::Bin::Xdotool => "xdotool".to_string(),
            argv_policy::Bin::Osascript => "osascript".to_string(),
            // Resolve cliclick to the path probed at startup (macOS-only field).
            argv_policy::Bin::Cliclick => {
                #[cfg(target_os = "macos")]
                {
                    self.cliclick_path
                        .clone()
                        .unwrap_or_else(|| "cliclick".to_string())
                }
                #[cfg(not(target_os = "macos"))]
                {
                    "cliclick".to_string()
                }
            }
        };

        let mut cmd = ProcessCommand::new(&program);
        cmd.args(args);
        // xdotool needs DISPLAY; harmless for the others.
        let display = std::env::var("DISPLAY").unwrap_or_else(|_| ":0".to_string());
        cmd.env("DISPLAY", display);

        let output = cmd.output().map_err(|e| {
            error!("Failed to execute {}: {}", program, e);
            format!("Execution error: {}", e)
        })?;

        let stderr = String::from_utf8_lossy(&output.stderr).to_string();

        if !output.status.success() {
            error!("Command failed: {}", stderr);
            return Err(stderr);
        }

        // xdotool exits 0 after dropping a key it cannot resolve, logging only
        // "No such key name '<x>'. Ignoring it." on stderr. The remaining modifiers
        // are still delivered, so the caller sees a successful command that did
        // something other than what was asked. Treat the warning as a failure.
        if stderr.contains("No such key name") {
            error!("Command dropped a key: {}", stderr);
            return Err(stderr.trim().to_string());
        }

        Ok(())
    }
}

// Implement the gRPC service
#[tonic::async_trait]
impl AgentService for AgentServiceImpl {
    async fn get_info(
        &self,
        _request: Request<InfoRequest>,
    ) -> Result<Response<AgentInfo>, Status> {
        info!("Agent info requested");
        
        Ok(Response::new(AgentInfo {
            os: self.os_type as i32,
            os_version: self.os_version.clone(),
            capabilities: self.capabilities.clone(),
            agent_version: env!("CARGO_PKG_VERSION").to_string(),
        }))
    }
    
    // Retired. ExecuteRequest carries only a shell string; commands arrive over the
    // server stream as structured argv and are handled by execute_command_argv.
    // The agent binds no gRPC listener, so this exists only to satisfy the trait.
    async fn execute(
        &self,
        _request: Request<ExecuteRequest>,
    ) -> Result<Response<ExecuteResponse>, Status> {
        Err(Status::unimplemented(
            "Execute is retired: commands are delivered as argv over the agent stream",
        ))
    }

    async fn ping(
        &self,
        _request: Request<PingRequest>,
    ) -> Result<Response<PongResponse>, Status> {
        Ok(Response::new(PongResponse { alive: true }))
    }
}

// Main function to start the agent
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    tracing_subscriber::fmt::init();
    
    info!("Control Center Agent v{}", env!("CARGO_PKG_VERSION"));
    info!("Starting Agent...");
    
    // Create agent service (keeps all execution logic)
    let service = AgentServiceImpl::new();
    let os_type = service.os_type;
    let os_version = service.os_version.clone();
    let capabilities = service.capabilities.clone();
    
    // Read server connection info from environment
    let server_host = std::env::var("AGENT_SERVER_HOST")
        .unwrap_or_else(|_| "127.0.0.1".to_string());
    let server_port = std::env::var("AGENT_SERVER_PORT")
        .unwrap_or_else(|_| "50051".to_string())
        .parse()
        .unwrap_or(50051);
    
    info!("Connecting to server at {}:{}...", server_host, server_port);
    
    // Build agent identity
    let agent_identity = identity::build_agent_identity(
        os_type,
        os_version,
        capabilities,
        env!("CARGO_PKG_VERSION").to_string(),
    );
    
    // Validate identity
    if let Err(e) = identity::validate_agent_identity(&agent_identity) {
        error!("Invalid agent identity: {}", e);
        return Err(e.into());
    }
    
    // Create connection manager
    let auth_token = std::env::var("CONTROL_CENTER_TOKEN").ok();
    let connection_manager = connection::ConnectionManager::new(
        server_host,
        server_port,
        agent_identity,
        auth_token.clone(),
    );
    
    // Connect and register
        match connection_manager.connect_and_register().await {
        Ok(mut client) => {
            info!("✓ Ready to accept commands");
            
            let agent_start_time = std::time::Instant::now();
            let commands_executed = std::sync::Arc::new(tokio::sync::RwLock::new(0u64));
            let commands_failed = std::sync::Arc::new(tokio::sync::RwLock::new(0u64));
            let (agent_tx, agent_rx) = tokio::sync::mpsc::channel(100);
            
            // Start bidirectional stream with server
            info!("Starting bidirectional stream with server...");
            let request_stream = tokio_stream::wrappers::ReceiverStream::new(agent_rx);

            // Authenticate the stream: attach the agent JWT as Bearer metadata so the
            // server can verify and bind it (F2).
            let mut stream_request = Request::new(request_stream);
            if let Some(token) = &auth_token {
                match format!("Bearer {}", token).parse() {
                    Ok(value) => { stream_request.metadata_mut().insert("authorization", value); }
                    Err(e) => { error!("Invalid CONTROL_CENTER_TOKEN for stream metadata: {}", e); }
                }
            }

            let response = match client.agent_stream(stream_request).await {
                Ok(resp) => resp,
                Err(e) => {
                    error!("Failed to start agent stream: {}", e);
                    return Err(e.into());
                }
            };
            
            let mut server_stream = response.into_inner();
            info!("✓ Bidirectional stream established");
            
            // Get connection ID for heartbeats
            let connection_id = connection_manager.get_connection_id().await
                .ok_or_else(|| {
                    error!("No connection ID available");
                    "No connection ID"
                })?;
            
            // Spawn heartbeat sender with REAL metrics
            let heartbeat_tx = agent_tx.clone();
            let heartbeat_conn_id = connection_id.clone();
            let heartbeat_start_time = agent_start_time;
            let heartbeat_executed = commands_executed.clone();
            let heartbeat_failed = commands_failed.clone();
            
            tokio::spawn(async move {
                let mut interval = tokio::time::interval(tokio::time::Duration::from_secs(30));
                loop {
                    interval.tick().await;
                    
                    // Calculate REAL uptime
                    let uptime_seconds = heartbeat_start_time.elapsed().as_secs();
                    
                    // Get REAL command counts
                    let executed = *heartbeat_executed.read().await;
                    let failed = *heartbeat_failed.read().await;
                    
                    let heartbeat = proto::AgentHeartbeat {
                        connection_id: heartbeat_conn_id.clone(),
                        timestamp: chrono::Utc::now().timestamp(),
                        status: Some(proto::AgentStatus {
                            ready: true,
                            commands_executed: executed,
                            commands_failed: failed,
                            uptime_seconds: uptime_seconds as i64,
                            system_info: std::collections::HashMap::new(),
                        }),
                        current_command_id: None,
                    };
                    
                    let agent_msg = proto::AgentMessage {
                        connection_id: heartbeat_conn_id.clone(),
                        payload: Some(proto::agent_message::Payload::Heartbeat(heartbeat)),
                    };
                    
                    if heartbeat_tx.send(agent_msg).await.is_err() {
                        warn!("Failed to send heartbeat, stream may be closed");
                        break;
                    }
                    
                    debug!(
                        "Sent heartbeat - uptime: {}s, executed: {}, failed: {}",
                        uptime_seconds, executed, failed
                    );
                }
            });
            
            info!("Agent running. Press Ctrl+C to stop.");
            info!("Listening for commands from server...");
            info!("Full tracking enabled (commands, uptime, execution times)");

            // No button state carries into a freshly registered session. Redundant in
            // a process that connects once, but it keeps the invariant explicit if a
            // reconnect loop is ever added around this block.
            service.held_buttons.write().await.clear();


            // Both interactive (SIGINT) and supervised (SIGTERM) shutdowns have to
            // reach the cleanup below. SIGTERM is what a service manager, a container
            // stop and `Popen.terminate()` send; leaving it to the default handler
            // killed the process outright, so a button held at that moment stayed
            // physically down.
            let mut shutdown_signal = Box::pin(async {
                #[cfg(unix)]
                {
                    match tokio::signal::unix::signal(
                        tokio::signal::unix::SignalKind::terminate(),
                    ) {
                        Ok(mut sigterm) => tokio::select! {
                            _ = tokio::signal::ctrl_c() => "SIGINT",
                            _ = sigterm.recv() => "SIGTERM",
                        },
                        Err(e) => {
                            warn!("Could not install SIGTERM handler: {}", e);
                            let _ = tokio::signal::ctrl_c().await;
                            "SIGINT"
                        }
                    }
                }
                #[cfg(not(unix))]
                {
                    let _ = tokio::signal::ctrl_c().await;
                    "Ctrl+C"
                }
            });

            // Main command loop - listen for messages from server
            loop {
                tokio::select! {
                    // Handle an interactive or supervised shutdown
                    signal = &mut shutdown_signal => {
                        info!("Received {}, shutting down...", signal);

                        // Send disconnect message
                        let disconnect = proto::DisconnectNotice {
                            reason: format!("Agent received {}", signal),
                            timestamp: chrono::Utc::now().timestamp(),
                            graceful: true,
                        };
                        
                        let agent_msg = proto::AgentMessage {
                            connection_id: connection_id.clone(),
                            payload: Some(proto::agent_message::Payload::Disconnect(disconnect)),
                        };
                        
                        let _ = agent_tx.send(agent_msg).await;
                        
                        break;
                    }
                    
                    // Handle incoming messages from server
                    server_msg = server_stream.message() => {
                        match server_msg {
                            Ok(Some(msg)) => {
                                match msg.payload {
                                    Some(proto::server_message::Payload::CommandRequest(cmd_req)) => {
                                        let command_id = cmd_req.id.clone();

                                        // Track command execution time
                                        let cmd_start_time = std::time::Instant::now();

                                        // Structured argv is the only accepted form; the legacy
                                        // shell-string field is rejected without executing.
                                        let human_cmd = cmd_req.human_command.clone();
                                        let malformed = if cmd_req.argv.is_empty() {
                                            Some("argv is required: the legacy shell command field is no longer accepted")
                                        } else if human_cmd.is_empty() {
                                            Some("human_command is required alongside argv")
                                        } else {
                                            None
                                        };

                                        debug!("Received command: {} (ID: {})", human_cmd, command_id);

                                        let (result, position, action) = match malformed {
                                            Some(reason) => {
                                                warn!("Rejected command {}: {}", command_id, reason);
                                                (
                                                    Err(reason.to_string()),
                                                    MousePosition { x: 0, y: 0, captured: false },
                                                    service.parse_action_details(&human_cmd),
                                                )
                                            }
                                            None => {
                                                service.execute_command_argv(&cmd_req.argv, &human_cmd).await
                                            }
                                        };

                                        let execution_time = cmd_start_time.elapsed();

                                        // Ground truth for the recorded event: what actually
                                        // ran, independent of the caller-supplied
                                        // human_command that drives the display string.
                                        let mut executed_meta = std::collections::HashMap::new();
                                        executed_meta.insert(
                                            "argv".to_string(),
                                            cmd_req.argv.join("\u{1f}"),
                                        );
                                        // Buttons still down, so the console can warn
                                        // rather than let a hold go unnoticed. Uses the
                                        // existing metadata map — no new RPC, and so no
                                        // new authorisation decision.
                                        executed_meta.insert(
                                            "held_buttons".to_string(),
                                            service.held_buttons_summary().await,
                                        );

                                        // Build response and update counters
                                        let response = match result {
                                            Ok(_) => {
                                                *commands_executed.write().await += 1;

                                                let message = service.build_detailed_message(
                                                    &action, &position, &human_cmd,
                                                );

                                                debug!(
                                                    "Command {} executed successfully (time: {:?})",
                                                    command_id,
                                                    execution_time
                                                );

                                                proto::CommandResponse {
                                                    id: command_id.clone(),
                                                    success: true,
                                                    message,
                                                    execution_time_ms: execution_time.as_millis() as i64,
                                                    mouse_x: if position.captured { Some(position.x) } else { None },
                                                    mouse_y: if position.captured { Some(position.y) } else { None },
                                                    position_captured: Some(position.captured),
                                                    metadata: executed_meta,
                                                }
                                            }
                                            Err(e) => {
                                                // Increment failure counter
                                                *commands_failed.write().await += 1;

                                                error!(
                                                    "Command {} failed: {} (time: {:?})",
                                                    command_id,
                                                    e,
                                                    execution_time
                                                );

                                                proto::CommandResponse {
                                                    id: command_id.clone(),
                                                    success: false,
                                                    message: format!("Execution error: {}", e),
                                                    execution_time_ms: execution_time.as_millis() as i64,
                                                    mouse_x: None,
                                                    mouse_y: None,
                                                    position_captured: None,
                                                    metadata: executed_meta,
                                                }
                                            }
                                        };
                                        
                                        // Send response back to server
                                        let agent_msg = proto::AgentMessage {
                                            connection_id: connection_id.clone(),
                                            payload: Some(proto::agent_message::Payload::CommandResponse(response)),
                                        };
                                        
                                        if agent_tx.send(agent_msg).await.is_err() {
                                            error!("Failed to send command response, stream closed");
                                            break;
                                        }
                                        
                                        debug!("Sent command response for {}", command_id);
                                    }
                                    
                                    Some(proto::server_message::Payload::Heartbeat(_heartbeat)) => {
                                        debug!("Received heartbeat from server");
                                        // Server is alive, no action needed
                                    }
                                    
                                    Some(proto::server_message::Payload::Disconnect(notice)) => {
                                        warn!("Server requested disconnect: {}", notice.reason);
                                        break;
                                    }
                                    
                                    Some(proto::server_message::Payload::ConfigUpdate(config)) => {
                                        debug!("Received config update from server");
                                        // Log the settings being updated
                                        for (key, value) in config.settings.iter() {
                                            debug!("Config update: {} = {}", key, value);
                                        }
                                        // Config updates can be implemented in the future if needed
                                    }
                                    
                                    None => {
                                        warn!("Received message with no payload");
                                    }
                                }
                            }
                            Ok(None) => {
                                info!("Server closed stream");
                                break;
                            }
                            Err(e) => {
                                error!("Stream error: {}", e);
                                break;
                            }
                        }
                    }
                }
            }
            
            // Every exit path from the command loop lands here — Ctrl+C, a server
            // disconnect notice, the stream closing, and a stream error — so this is
            // the single place a button left down can be cleaned up.
            service.release_held_buttons().await;

            // Print final statistics on shutdown
            let final_executed = *commands_executed.read().await;
            let final_failed = *commands_failed.read().await;
            let final_uptime = agent_start_time.elapsed();
            
            info!("═══════════════════════════════════════");
            info!("Agent Shutdown Statistics");
            info!("═══════════════════════════════════════");
            info!("  Uptime: {:.2}h ({:.0}s)", 
                final_uptime.as_secs_f64() / 3600.0,
                final_uptime.as_secs_f64());
            info!("  Commands executed: {}", final_executed);
            info!("  Commands failed: {}", final_failed);
            info!("  Success rate: {:.2}%", 
                if final_executed + final_failed > 0 {
                    (final_executed as f64 / (final_executed + final_failed) as f64) * 100.0
                } else {
                    0.0
                });
            info!("═══════════════════════════════════════");
        }
        Err(e) => {
            error!("Failed to connect: {}", e);
            return Err(e);
        }
    }
    
    Ok(())
}

// Unit tests for OS detection and command validation
#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_os_detection() {
        let (_os_type, version) = AgentServiceImpl::detect_os_version();
        assert!(!version.is_empty());
        assert!(!version.contains("Unknown") || cfg!(debug_assertions));
    }
    
}